### ISSUE TITLE
Error while creating alarm using openstack4j-3.0.3-withdeps.jar

### ISSUE THREAD

**Issue by prashr186** [ContainX/openstack4j#1016]
Hi ,
I am facing an issue while creating the alarm with openstack4j-3.0.3-withdeps.jar.
The source code is as follows:
`OSClient os = OSFactory.builderV2()
                .endpoint("http://172.16.1.100:5000/v2.0")
                .credentials("admin", "d285a35ac4d74a44")
                .tenantName("admin")
                .authenticate();
        System.out.println("testopenstack4j.TestOpenStack4j.main()" + os.getEndpoint());

        CeilometerThresholdRule ceilometerThresholdRule = new CeilometerThresholdRule();
        ceilometerThresholdRule.setComparisonOperator(Alarm.ThresholdRule.ComparisonOperator.GE);
        ceilometerThresholdRule.setEvaluationPeriods(1);
        ceilometerThresholdRule.setMeterName("cpu_util");
        ceilometerThresholdRule.setThreshold(3);

        List<String> alarmActions = new ArrayList<>();
        List<String> oKActions = new ArrayList<>();

        alarmActions.add("http://192.168.8.56:5000/alarm/instance_TOO_HOT");

        oKActions.add("http://192.168.8.56:5000//alarm/instance_NO_DATA");

        Alarm alarm = Builders.alarm().name("high_Cpu1").description("testcpu-high")
                .type(Alarm.Type.THRESHOLD).thresholeRule(ceilometerThresholdRule).alarmActions(alarmActions).okActions(oKActions).isEnabled(true).build();

        Alarm alarm2 = os
                .telemetry()
                .alarms()
                .create(alarm);
        System.out.println("Alarm details:" + alarm2.getAlarmId());
        System.out.println("alarms:" + os.telemetry().alarms().list());`

The Error is 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
testopenstack4j.TestOpenStack4j.main()http://172.16.1.100:5000/v2.0
Exception in thread "main" org.jboss.resteasy.client.ClientResponseFailure: Unable to find a MessageBodyReader of content-type text/plain;charset="UTF-8" and type null
	at org.jboss.resteasy.client.core.BaseClientResponse.createResponseFailure(BaseClientResponse.java:523)
	at org.jboss.resteasy.client.core.BaseClientResponse.createResponseFailure(BaseClientResponse.java:514)
	at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:415)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:377)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:350)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:344)
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.readEntity(HttpResponseImpl.java:116)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:66)
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.getEntity(HttpResponseImpl.java:64)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:220)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:202)
	at org.openstack4j.openstack.telemetry.internal.AlarmServiceImpl.create(AlarmServiceImpl.java:55)
	at os_new.OS_new.main(OS_new.java:53)
/home/prashanthk@sawridge.com/.cache/netbeans/8.1/executor-snippets/run.xml:53: Java returned: 1

**Comment by auhlig** [comment]
Could you try with the latest release, which is 3.0.4 ?

**Comment by auhlig** [comment]
Also choosing a different connector might do the trick.
