### ISSUE TITLE
Can not deserialize instance of java.lang.String when listing images v2 with locations array in them.

### ISSUE THREAD

**Issue by pstoyanov91** [ContainX/openstack4j#1018]
Getting this exception when trying to list v2 Images with locations. The request doesn't fail if there are no locations or when I use v1 Images.

`Exception in thread "main" org.jboss.resteasy.spi.ReaderException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: org.jboss.resteasy.client.core.SelfExpandingBufferredInputStream@3e2055d6; line: 1, column: 269] (through reference chain: org.openstack4j.openstack.image.v2.domain.Images["images"]->java.util.ArrayList[0]->org.openstack4j.openstack.image.v2.domain.GlanceImage["locations"]->java.util.ArrayList[0])
	at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:469)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:377)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:350)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:344)
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.readEntity(HttpResponseImpl.java:116)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHa944 [main] DEBUG org.apache.http.impl.client.DefaultHttpClient  - Connection can be kept alive indefinitely
952 [main] DEBUG org.apache.http.wire  - << "{"images": [{"status": "active", "name": "ubuntu_image_from_sftp_url", "tags": [], "container_format": "bare", "created_at": "2017-05-03T14:37:22Z", "size": 324993024, "disk_format": "qcow2", "updated_at": "2017-05-03T14:46:48Z", "visibility": "public", "locations": [{"url": "file:///var/lib/glance/images/b5d93352-de19-476f-bfa3-11ef12582c80", "metadata": {}}], "self": "/v2/images/b5d93352-de19-476f-bfa3-11ef12582c80", "min_disk": 0, "protected": false, "id": "b5d93352-de19-476f-bfa3-11ef12582c80", "file": "/v2/images/b5d93352-de19-476f-bfa3-11ef12582c80/file", "checksum": "c35e305bf7571ee7b08528acbe7eec26", "owner": "4331967e76c64c18b0ccbb708817e0a7", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}, {"status": "active", "virtual_size": null, "description": "http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img", "tags": [], "container_format": "bare", "created_at": "2017-04-06T12:33:49Z", "size": 324993024, "disk_format": "qcow2", "locations": [{"url": "http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img", "metadata": {}}], "visibility": "public", "updated_at": "2017-04-06T12:33:49Z", "self": "/v2/images/874b4894-695c-46ab-bbfe-4c25590682ee", "min_disk": 0, "protected": false, "id": "874b4894-695c-46ab-bbfe-4c25590682ee", "file": "/v2/images/874b4894-695c-46ab-bbfe-4c25590682ee/file", "checksum": null, "owner": "4331967e76c64c18b0ccbb708817e0a7", "schema": "/v2/schemas/image", "min_ram": 0, "name": "ubuntu 16.4"}, {"status": "active", "name": "Ubuntu Server", "tags": [], "container_format": "bare", "created_at": "2017-02-24T15:59:02Z", "size": 324075520, "disk_format": "qcow2", "updated_at": "2017-02-24T15:59:03Z", "visibility": "public", "locations": [{"url": "file:///var/lib/glance/images/5a394630-45d8-44ec-8682-646a1a3ae790", "metadata": {}}], "self": "/v2/images/5a394630-45d8-44ec-8682-646a1a3ae790", "min_disk": 0, "protected": false, "id": "5a394630-45d8-44ec-8682-646a1a3ae790", "file": "/v2/images/5a394630-45d8-44ec-8682-646a1a3ae790/file", "checksum": "0ba9b9244c06a1287422735fd65b28f7", "owner": "4331967e76c64c18b0ccbb708817e0a7", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}, {"status": "active", "name": "cirros", "tags": [], "container_format": "bare", "created_at": "2016-12-23T07:59:27Z", "size": 13287936, "disk_format": "qcow2", "updated_at": "2016-12-23T07:59:48Z", "visibility": "public", "locations": [{"url": "file:///var/lib/glance/images/82ec322d-a5f5-4246-8e07-49dd072554e2", "metadata": {}}], "self": "/v2/images/82ec322d-a5f5-4246-8e07-49dd072554e2", "min_disk": 0, "protected": false, "id": "82ec322d-a5f5-4246-8e07-49dd072554e2", "file": "/v2/images/82ec322d-a5f5-4246-8e07-49dd072554e2/file", "checksum": "ee1eca47dc88f4879d8a229cc70a07c6", "owner": "f11d2e793d3247cea344d3178acef921", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/imagendler.java:66)
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.getEntity(HttpResponseImpl.java:64)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:220)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:202)
	at org.openstack4j.openstack.image.v2.internal.ImageServiceImpl.list(ImageServiceImpl.java:45)
	at com.mycompany.mavenproject.Application.main(Application.java:41)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: org.jboss.resteasy.client.core.SelfExpandingBufferredInputStream@3e2055d6; line: 1, column: 269] (through reference chain: org.openstack4j.openstack.image.v2.domain.Images["images"]->java.util.ArrayList[0]->org.openstack4j.openstack.image.v2.domain.GlanceImage["locations"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingE"}], "schema": "/v2/schemas/images", "first": "/v2/images"}"
967 [main] DEBUG org.apache.http.impl.conn.SingleClientConnManager  - Releasing connection org.apache.http.impl.conn.SingleClientConnManager$ConnAdapter@28194a50
xception.java:216)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:873)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:845)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:206)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1534)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:944)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:811)
	at org.jboss.resteasy.core.interception.MessageBodyReaderContextImpl.proceed(MessageBodyReaderContextImpl.java:105)
	at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:433)
	... 10 more`

**Comment by YeonSeoMom** [comment]
I have the same problem. When will it be fiexed?

**Comment by vinodborole** [comment]
@pstoyanov91  @YeonSeoMom  There is a fix for this already, the PR is in review #1096 at this stage

**Comment by jdanekrh** [comment]
This appears fixed in 3.1.1-SNAPSHOT as of now. 3.1.0 is still buggy. I just tried it.
