### ISSUE TITLE
download object throw stream closed

### ISSUE THREAD

**Issue by coxon** [ContainX/openstack4j#1035]
my code is : 
DLPayload payload = osClientV3.objectStorage().objects().download(bucket, object, downloadOptions);
and this throw stream closed, its not happen every time.

**Comment by coxon** [comment]
exception infomation:
openstack4j version:3.0.3
jboss resteasy version : 3.0.23.Final

code : 
try(InputStream inputStream = dlPayload.getHttpResponse().getInputStream()){
                ByteStreams.copy(inputStream, byteArrayOutputStream);
}catch(IOException e){}

java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:283)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:110)

**Comment by auhlig** [comment]
Hi @coxon,
Which version of OS4j and which connector did you use? Did you try multiple connectors?

**Comment by coxon** [comment]
hello @auhlig, os4j version is 3.0.3.  and with default dependency connectors (os4j-resteasy:3.0.3).
how to use multiple connectors?

**Comment by auhlig** [comment]
Could you upgrade to OpenStack4j 3.0.4 and check if the problem persists? I meant trying a different connector.

**Comment by coxon** [comment]
@auhlig  ok. i will try 3.0.4
any suggestion of other connectors ?

**Comment by coxon** [comment]
Hi @auhlig ,  its looks ok atfer i changed connector to jersey. thanks a lot.
