### ISSUE TITLE
Issue while using Openstanck4j  , NoClassDefFoundError

### ISSUE THREAD

**Issue by kushalagrawal1** [ContainX/openstack4j#1057]
Hi,

I am getting this error while trying to connect to OpenStack using the openstack4j client (Version 3.0.4). Which says:

**Caused by: java.lang.NoClassDefFoundError: org/openstack4j/openstack/logging/LoggerFactory**
        at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.<clinit>(HttpExecutorServiceImpl.java:24) [openstack4j-httpclient-2.20.jar:]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_141]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [rt.jar:1.7.0_141]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.7.0_141]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [rt.jar:1.7.0_141]
        at java.lang.Class.newInstance(Class.java:383) [rt.jar:1.7.0_141]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:373) [rt.jar:1.7.0_141]
        ... 55 more
Caused by: java.lang.ClassNotFoundException: org.openstack4j.openstack.logging.LoggerFactory

**Comment by vinodborole** [comment]
@kushalagrawal1 can you please check your dependencies? Also, can you try the latest release.

**Comment by jyfar** [comment]
If you're not using the jar withdeps then you need to add to the classpath all the required third party librairies, see: http://www.openstack4j.com/learn/getting-started

I share with you logging dependencies in my maven project: 

```
<!-- https://mvnrepository.com/artifact/log4j/log4j -->
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
<!-- https://mvnrepository.com/artifact/commons-logging/commons-logging -->
        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>1.2</version>
        </dependency>
<dependency>

            <groupId>org.slf4j</groupId>

            <artifactId>slf4j-api</artifactId>

            <version>${slf4jVersion}</version>

        </dependency>

        <dependency>

        <groupId>org.slf4j</groupId>

        <artifactId>slf4j-log4j12</artifactId>

        <version>${slf4jVersion}</version>

    </dependency>
```

**Comment by kushalagrawal1** [comment]
Thank you @vinodborole @jyfar.yes it was because of my dependency issue. at a distant dependency in the application, it was loading 2.x httpclient.
