### ISSUE TITLE
ClassCastException in Resteasy connector

### ISSUE THREAD

**Issue by bzhou003** [ContainX/openstack4j#1069]
My company are using openstack4j for swift product. Recently we upgrade openstack4j to 3.0.3. But got this exception:

`
java.lang.ClassCastException: org.glassfish.jersey.server.internal.RuntimeDelegateImpl cannot be cast to org.jboss.resteasy.spi.ResteasyProviderFactory
at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:353)
at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.checkClientExceptionMapper(ApacheHttpClient4Executor.java:72)
at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.<init>(ApacheHttpClient4Executor.java:126)
at org.openstack4j.connectors.resteasy.executors.ApacheHttpClientExecutor.<init>(ApacheHttpClientExecutor.java:24)
at org.openstack4j.connectors.resteasy.executors.ApacheHttpClientExecutor.create(ApacheHttpClientExecutor.java:48)
at org.openstack4j.connectors.resteasy.HttpCommand.initialize(HttpCommand.java:43)
at org.openstack4j.connectors.resteasy.HttpCommand.create(HttpCommand.java:37)
at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:51)
at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:154)
at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:70)
at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:165)
at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:128)
`

I did some investigation, found it may be caused by the old version of RestEasy as mentioned here:
https://stackoverflow.com/questions/36550057/cast-exception-with-resteasy

Right now, openstack4j use 2.3.7.Final, but the newest version is 3.1.3.Final. I wonder would upgrade RestEasy could solve the problem here. Thanks.

**Comment by vinodborole** [comment]
@bzhou003 It should fix the problem, let us know if does not

**Comment by auhlig** [comment]
If it works, would you like to submit a PR to update resteasy @bzhou003?

**Comment by whydejavu** [comment]
I have the same problem whith openstack4j 3.0.4

**Comment by koztom** [comment]
Anyone solve it?
