### ISSUE TITLE
Is V3 Identity Authentication compatible with JDK 1.6?If yes, which and how should I make use of it?

### ISSUE THREAD

**Issue by RGLin** [ContainX/openstack4j#1071]
Greetings,

I am just wondering if the OSFactory.builderV3() method can run on JDK 1.6.

It returns the following error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openstack4j/openstack/OSFactory : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at Test.main(Test.java:9)

I do know there is a Jersy2JDK1.6 connector works on Keystone V2, like:
                 <dependency>
			  <groupId>org.pacesys</groupId>
			  <artifactId>openstack4j-core</artifactId>
			  <version>3.0.0</version>
		</dependency>
		<dependency>
			  <groupId>org.pacesys.openstack4j.connectors</groupId>
			  <artifactId>openstack4j-jersey2-jdk1.6</artifactId>
			  <version>3.0.0</version>
		</dependency>
but in terms of my project, it requires V3 Authentication.

Is there any jdk1.6 connector that support V3?

**Comment by auhlig** [comment]
AFAIK JDK 1.6 is EOL for a while now. 
According to our readme OpenStack4j requires at least JDK 1.7.
