### ISSUE TITLE
Authorization exception while trying to access Openstack

### ISSUE THREAD

**Issue by kailashperi** [ContainX/openstack4j#1101]
I am trying to authenticate with Openstack with the following code:

OSClientV3 os = OSFactory.builderV3()
                                .endpoint(auth_url)
                                .credentials (userId, password, Identifier.byName(domainName))
                                .scopeToProject(Identifier.byId(projectId))
                                .authenticate();

below are the credentials

        "auth_url": "https://identity.open.softlayer.com",
        "project": "object_storage_be0d0544_631c_4f56_ab42_e8ae146fdef2",
        "projectId": "acexxxxxxx",
        "region": "dallas",
        "userId": "a1aexxxxxxx",
        "username": "admin_xxxxxxxxxxxx",
        "password": "xxxxxxxxx",
        "domainId": "xxxxxxxxxxxxxxxx",
        "domainName": "99999",
        "role": "admin"

Can someone let me know if there is anything wrong with the above

**Comment by auhlig** [comment]
What's the exception?

**Comment by kailashperi** [comment]
It is : Exception in thread "main" AuthenticationException{message=Unauthorized, status=401}

I have tried 

OSClientV3 os = OSFactory.builderV3()
						.endpoint(auth_url)
						.credentials (userId, password, domainIdentifier)
						.authenticate();
as well with the same exception. However, I can curl and get successful results and can not get it to work with Java

**Comment by auhlig** [comment]
Is the initial authentication getting the 401 or a subsequent call? Are you sure you're sending the correct parameters? Usually the auth URL includes the port and looks like http(s)://<fqdn>:5000/v3.

**Comment by jachinte** [comment]
Hi @auhlig 
I, too, am getting an authorization exception:

```java
Exception in thread "main" AuthenticationException{message=Unauthorized, status=401}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:36)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:191)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:74)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:172)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:129)
	at com.rigiresearch.migueljimenez.Test.main(Test.java:49)
```

In my case, it's the initial authentication. In fact, this is my whole code:
```java
OSClientV3 os = OSFactory.builderV3()
                .endpoint("https://east.cloud.computecanada.ca:5000/v3")
                .credentials("USER-ID", "PASSWORD")
                .scopeToProject(Identifier.byId("PROJECT-ID"))
                .authenticate();
System.out.println(os.images().list());
```
Am I missing something? should I export environment variables or something similar?
I also tried using V2 client and URL, or adding the other parameters, but I get the same error and sometimes a bad request error.

Thank you

**Comment by auhlig** [comment]
Can you check http request and response? Is the initial authentication working or already failing? Or is the `401` the response to the image list?

**Comment by jachinte** [comment]
Thanks for the quick reply, @auhlig.
The exception is thrown from the `authenticate` method.
Could you please tell me how to check the HTTP request and response? I used `OSFactory.enableHttpLoggingFilter(true);` and a sample conf file but it didn't log any message.

**Comment by auhlig** [comment]
You're on the right track. Enabling the logging should do it. You set a proxy and catch the http traffic via tools like mitmproxy

**Comment by jachinte** [comment]
Here you have, @auhlig. The Exception occurs while executing `authenticate`.
```java
OSClientV3 os = OSFactory.builderV3()
                .withConfig(
                        Config.newConfig()
                            .withSSLVerificationDisabled()
                            .withProxy(new ProxyHost("http://localhost", 8080))
                    )
                .endpoint("https://east.cloud.computecanada.ca:5000/v3")
                .credentials("USER-ID", "PASSWORD")
                .scopeToProject(Identifier.byId("PROJECT-ID"))
                .authenticate();
```

![screen shot 2018-02-22 at 3 59 51 pm](https://user-images.githubusercontent.com/1284036/36571106-074e2e4a-17ea-11e8-94f7-66fed8bfb345.png)
![screen shot 2018-02-22 at 4 00 13 pm](https://user-images.githubusercontent.com/1284036/36571107-076aafa2-17ea-11e8-93c9-b1b839cd5315.png)

**Comment by jachinte** [comment]
I found the problem. Apparently, the user isn't scoped to a project/domain, so I used the following code and it worked:
```java
OSClientV3 os = OSFactory.builderV3()
            .endpoint("https://east.cloud.computecanada.ca:5000/v3")
            .credentials("USERNAME", "PASSWORD", Identifier.byName("DOMAIN-NAME"))
            .authenticate();
```
