### ISSUE TITLE
ProcessingException when calling "getStackByName"

### ISSUE THREAD

**Issue by rschollmeyer** [ContainX/openstack4j#1107]
When i call "public Stack getStackByName(String stackName)" in class "StackServiceImpl" i am getting the following exception

> Caused by: javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type text/plain;charset=UTF-8 and type class org.openstack4j.openstack.heat.domain.HeatStack
	at org.jboss.resteasy.core.interception.jaxrs.ClientReaderInterceptorContext.throwReaderNotFound(ClientReaderInterceptorContext.java:42)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.getReader(AbstractReaderInterceptorContext.java:80)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:53)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:266)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:196)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:218)
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.readEntity(HttpResponseImpl.java:118)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:66)
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.getEntity(HttpResponseImpl.java:64)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:225)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:207)
	at org.openstack4j.openstack.heat.internal.StackServiceImpl.getStackByName(StackServiceImpl.java:91)

I am using the 3.1.1-SNAPSHOT version and it worked all the time until i updated my forked repository today, now i get this. Any suggestion?

**Comment by auhlig** [comment]
Strange. Does it work with a different connector?

**Comment by rschollmeyer** [comment]
Thank you for your quick answer. I just tried every connector and it is acutally working with "okhttp" and "httpclient", but not with "jersey2" and "resteasy".

**Comment by vinodborole** [comment]
Closing the issue
