### ISSUE TITLE
openstack4j 3.1.0 jar is giving errors 

### ISSUE THREAD

**Issue by tajpasha** [ContainX/openstack4j#1155]
openstack4j 3.1.0 jar is giving errors , was using earlier the 3.0.0 version of openstack4j but no errors .

2018-02-23T11:03:01,420 [DEBUG] [org.jboss.resteasy.resteasy_jaxrs.i18n.LogMessages.<clinit>(LogMessages.java:27)] Logging Provider: org.jboss.logging.Log4j2LoggerProvider
2018-02-23T11:03:01,422 [DEBUG] [org.jboss.resteasy.plugins.providers.DocumentProvider.<init>(DocumentProvider.java:49)] Provider : org.jboss.resteasy.plugins.providers.DocumentProvider,  ethod : DocumentProvider
2018-02-23T11:03:01,453 [DEBUG] [org.jboss.resteasy.plugins.providers.DocumentProvider.<init>(DocumentProvider.java:59)] RESTEASY002330: Unable to retrieve config: expandEntityReferences dfaults to false
2018-02-23T11:03:01,456 [DEBUG] [org.jboss.resteasy.plugins.providers.DocumentProvider.<init>(DocumentProvider.java:68)] RESTEASY002335: Unable to retrieve config: enableSecureProcessingFeture defaults to true
2018-02-23T11:03:01,457 [DEBUG] [org.jboss.resteasy.plugins.providers.DocumentProvider.<init>(DocumentProvider.java:77)] RESTEASY002325: Unable to retrieve config: disableDTDs defaults to rue
2018-02-23T11:03:01,460 [DEBUG] [org.jboss.resteasy.plugins.providers.DocumentProvider.<init>(DocumentProvider.java:49)] Provider : org.jboss.resteasy.plugins.providers.DocumentProvider,  ethod : DocumentProvider
2018-02-23T11:03:01,462 [DEBUG] [org.jboss.resteasy.plugins.providers.DocumentProvider.<init>(DocumentProvider.java:59)] RESTEASY002330: Unable to retrieve config: expandEntityReferences dfaults to false
2018-02-23T11:03:01,463 [DEBUG] [org.jboss.resteasy.plugins.providers.DocumentProvider.<init>(DocumentProvider.java:68)] RESTEASY002335: Unable to retrieve config: enableSecureProcessingFeture defaults to true
2018-02-23T11:03:01,464 [DEBUG] [org.jboss.resteasy.plugins.providers.DocumentProvider.<init>(DocumentProvider.java:77)] RESTEASY002325: Unable to retrieve config: disableDTDs defaults to rue
java.lang.RuntimeException: java.lang.IllegalArgumentException: SSL socket factory may not be null
        at org.jboss.resteasy.client.jaxrs.ClientHttpEngineBuilder43.build(ClientHttpEngineBuilder43.java:164)
        at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.build(ResteasyClientBuilder.java:381)
        at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.build(ResteasyClientBuilder.java:35)

Caused by: java.lang.IllegalArgumentException: SSL socket factory may not be null
        at org.apache.http.util.Args.notNull(Args.java:54)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(SSLConnectionSocketFactory.java:296)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(SSLConnectionSocketFactory.java:263)
        at org.jboss.resteasy.client.jaxrs.ClientHttpEngineBuilder43$1.<init>(ClientHttpEngineBuilder43.java:82)
        at org.jboss.resteasy.client.jaxrs.ClientHttpEngineBuilder43.build(ClientHttpEngineBuilder43.java:82)
        ... 38 more

**Comment by auhlig** [comment]
We'll, since this is a community driven open-source project just saying openstack4j is giving errors and posting the stacktrace won't help. Can you provide more details and first analysis? What did you do? I also would highly appreciate if you consider submitting a PR, so we can actually work together on fixing things.

**Comment by tajpasha** [comment]
Agree, Let me give the context here .
		There was a Junit Test case which was working fine with openstack4j version 3.0 but when upgraded to 3.1 it started failing and here is the snippet.
		
		@RunWith(PowerMockRunner.class)
		@PrepareForTest({SSLContext.class, MyMmiClient.class})
		@PowerMockIgnore("javax.management.*") 
		public class MyClientTest
		{
		
		 @Test
		public void testDsrMmiClient()
		{
			MyClient dsrMmiClient = null;
			SSLContext sslContextMock = PowerMockito.mock(SSLContext.class);
    	    PowerMockito.mockStatic(SSLContext.class);
    	    Mockito.when(SSLContext.getInstance(Mockito.anyString())).thenReturn(sslContextMock);
    	    
	        dsrMmiClient = new MyClient();
		}
		}
		
		
		//Here is the source code .
		
		import javax.ws.rs.client.Client;
		import javax.net.ssl.SSLContext;
		
		public class MyClient
		{
		Client client = null;
 
		public MyClient() throws Exception
		{
		SSLContext sslContext = SSLContext.getInstance("SSL");
		
		// Instance of the clientTrustManager which implements X509TrustManager to verify whether the Host is valid
		MyClientTrustManager clientTrustManager = new MyClientTrustManager();
		
		// Initialize the SSL context object with the TrustManager
		sslContext.init(null, new javax.net.ssl.TrustManager[] { clientTrustManager }, null);
			
		client = ClientBuilder.newBuilder().property(ClientProperties.CONNECT_TIMEOUT, CONNECT_TIMEOUT)
				   						   .property(ClientProperties.READ_TIMEOUT, READ_TIMEOUT)
										   .sslContext(sslContext)
		        						   .hostnameVerifier(getHostnameVerifier())
		        						   .build();
										   }
										   
		}

**Comment by auhlig** [comment]
java.lang.IllegalArgumentException: SSL socket factory may not be null
