### ISSUE TITLE
org.apache.http.ProtocolException: Content-Length header already present

### ISSUE THREAD

**Issue by JialeiWu** [ContainX/openstack4j#1206]
when I use os.objectStorage().objects().copy(ObjectLocation.create(srcContainer, srcObject)
                                                ,ObjectLocation.create(destContainer, destObject)
                                                ), find error as follow:
Caused by: org.apache.http.client.ClientProtocolException
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient
4Engine.java:312)
        ... 97 more
Caused by: org.apache.http.ProtocolException: Content-Length header already present
        at org.apache.http.protocol.RequestContent.process(RequestContent.java:97)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:183)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        ... 100 more
I think the errors are caused by  Content-Length assigned by the copy() method，but the copy() method is protected so I can't change it.

**Comment by hasti123** [comment]
I'm getting this same issue, any updates?
