### ISSUE TITLE
I am getting java.lang.NoSuchFieldError: EXCLUDE_EMPTY

### ISSUE THREAD

**Issue by g-g-n** [ContainX/openstack4j#123]
I am trying to authenticate and get the OSClient, but getting error

OSClient os = OSFactory.builder()
                       .endpoint("http://127.0.0.1:5000/v2.0")
                       .credentials("admin","sample")
                       .tenantName("admin")
                       .authenticate();

Error -
Exception in thread "main" com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchFieldError: EXCLUDE_EMPTY
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2261)
    at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4004)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
    at org.openstack4j.connectors.jersey2.ClientFactory.create(ClientFactory.java:50)
    at org.openstack4j.connectors.jersey2.HttpCommand.initialize(HttpCommand.java:48)
    at org.openstack4j.connectors.jersey2.HttpCommand.create(HttpCommand.java:43)
    at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:53)
    at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
    at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
    at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:77)
    at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:41)
    at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:84)
    at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:65)
    at dis.vs.openstack.DISVSOpenStackController.main(DISVSOpenStackController.java:14)
Caused by: java.lang.NoSuchFieldError: EXCLUDE_EMPTY
    at org.glassfish.jersey.client.ClientConfig$State.<init>(ClientConfig.java:147)
    at org.glassfish.jersey.client.ClientConfig.<init>(ClientConfig.java:457)
    at org.glassfish.jersey.client.JerseyClientBuilder.<init>(JerseyClientBuilder.java:94)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at java.lang.Class.newInstance(Class.java:374)
    at javax.ws.rs.client.FactoryFinder.newInstance(FactoryFinder.java:116)
    at javax.ws.rs.client.FactoryFinder.find(FactoryFinder.java:206)
    at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:86)
    at org.openstack4j.connectors.jersey2.ClientFactory.buildClientFromConfig(ClientFactory.java:57)
    at org.openstack4j.connectors.jersey2.ClientFactory.access$100(ClientFactory.java:31)
    at org.openstack4j.connectors.jersey2.ClientFactory$1.load(ClientFactory.java:39)
    at org.openstack4j.connectors.jersey2.ClientFactory$1.load(ClientFactory.java:36)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2257)
    ... 14 more

**Comment by sunilhcl** [comment]
Please share the resolution. As i am also getting the same problem

**Comment by codestrong** [comment]
I had the same error with another library. My wadl-core:1.1.6 required jersey-common:2.5.1. At the same time I used jersey-client:2.20 which required jersey-common:2.20. That was the problem.

**Comment by kemkem** [comment]
I got this error recently, jersy-common was missing.

Complete maven depencies : 
<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-client</artifactId>
			<version>2.26</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-common</artifactId>
			<version>2.26</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-json-jackson</artifactId>
			<version>2.26</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.inject</groupId>
			<artifactId>jersey-hk2</artifactId>
			<version>2.26</version>
		</dependency>
