### ISSUE TITLE
ByteArray streams should not be used for downloading images from Glance

### ISSUE THREAD

**Issue by pk044** [ContainX/openstack4j#1239]
```
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at org.jboss.resteasy.util.ReadFromStream.readFromStream(ReadFromStream.java:33)
        at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.bufferEntity(ClientResponse.java:322)
        at org.openstack4j.connectors.resteasy.HttpResponseImpl.getInputStream(HttpResponseImpl.java:87)
        at org.openstack4j.openstack.image.v2.internal.ImageServiceImpl.download(ImageServiceImpl.java:160)
```

`client.imagesV2().download(image.getId(), new File(destination));`

API is trying to load the image to RAM - this means I'd have to buy ~20GB more ram than I currently have, because most images are usually that size :) The stacktrace above is a result of an attempt of triyng to download a 900MB image from Glance.

Using buffered streams might be a better idea here. What do you guys think?

**Comment by pk044** [comment]
Ok - I spent a little bit more time on it and found out there is no code change neccessary. All you have to do is to replace the Jersey http client, simply by replacing the connector, e.g.

```
        <dependency>
            <groupId>org.pacesys.openstack4j.connectors</groupId>
            <artifactId>openstack4j-okhttp</artifactId>
            <version>3.1.0</version>
        </dependency>
```

Jersey returns a ByteArrayInputStream of the response content - so it simply won't work out with Glance API.

OkHttp seems to have predicted this issue - it handles large response content.

So the final solution to the problem would probably just be updating the documentation, just by giving a warning that Jersey might be insufficient for operations like image download (I guess the same would be applied for Swift?)

By the way, thanks for putting the effort into making this API for Java - it's great.
