### ISSUE TITLE
java.lang.NullPointerException when rebootGuest is called

### ISSUE THREAD

**Issue by Dhanusha-Jeevan** [ContainX/openstack4j#1318]
Hi,

java.lang.NullPointerException: null at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) \~\[guava-20.0.jar:?\] at org.openstack4j.openstack.compute.internal.ServerServiceImpl.reboot(ServerServiceImpl.java:211) \~\[openstack4j-3.2.0.jar:?\] at com.nsn.cpf.vManager.OpenStackImplV3.rebootGuest(OpenStackImplV3.java:120) 

i am getting below error when serverID is passed to rebootGuest.

`public void rebootGuest(String vmName) throws Exception {
        reConnect();
        ActionResponse response = os.compute().servers().reboot(getIdByHostName(vmName), RebootType.SOFT);
}`

please suggest what could be the cause and help in resolving the issue.
Thanks in advance

**Comment by bboyHan** [comment]
good issue. forked from https://github.com/openstack4j/openstack4j  .

consider to solve it
