### ISSUE TITLE
openstack4j 2.0.0-SNAPSHOT compatible with java 1.6??

### ISSUE THREAD

**Issue by vinodborole** [ContainX/openstack4j#134]
I am using openstack4j 2.0.0-Snapshot with java 1.6 and a basic authentication code is throwing me below jersey error

Exception in thread "main" com.google.common.util.concurrent.ExecutionError: java.lang.UnsupportedClassVersionError: org/glassfish/jersey/jackson/JacksonFeature : Unsupported major.minor version 51.0
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
        at org.openstack4j.connectors.jersey2.ClientFactory.create(ClientFactory.java:50)
        at org.openstack4j.connectors.jersey2.HttpCommand.initialize(HttpCommand.java:50)
        at org.openstack4j.connectors.jersey2.HttpCommand.create(HttpCommand.java:45)
        at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:53)
        at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
        at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
        at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:77)
        at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:41)
        at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:84)
        at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:65)
        at com.osp4j.Osp4jApp.main(Osp4jApp.java:33)
Caused by: java.lang.UnsupportedClassVersionError: org/glassfish/jersey/jackson/JacksonFeature : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at org.openstack4j.connectors.jersey2.ClientFactory.buildClientFromConfig(ClientFactory.java:57)
        at org.openstack4j.connectors.jersey2.ClientFactory.access$100(ClientFactory.java:31)
        at org.openstack4j.connectors.jersey2.ClientFactory$1.load(ClientFactory.java:39)
        at org.openstack4j.connectors.jersey2.ClientFactory$1.load(ClientFactory.java:36)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        ... 14 more

Pom.xml

<dependency>
  <groupId>org.pacesys</groupId>
  <artifactId>openstack4j</artifactId>
  <version>2.0.0-SNAPSHOT</version>
</dependency>

Code:
        final OSClient os = OSFactory.builder().endpoint(serverUrl).credentials(username, credential).tenantName(tenant).authenticate();

**Comment by mnkanojia** [comment]
I recently started working on writing a Openstack client and getting the same error that vinodborole mentioned above.
Our application is on JDK1.6 and Jersey 2.0. I am using openstack4j 2.0.1 and as mentioned by gondor, I have openstack4j-jersey2-jdk16-2.0.1 in the classpath as well.

Can someone please tell me how to get rid of this exception:

Exception in thread "main" com.google.common.util.concurrent.ExecutionError: java.lang.UnsupportedClassVersionError: org/glassfish/jersey/jackson/JacksonFeature : Unsupported major.minor version 51.0
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2261)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4004)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
	at org.openstack4j.connectors.jersey2.ClientFactory.create(ClientFactory.java:50)
	at org.openstack4j.connectors.jersey2.HttpCommand.initialize(HttpCommand.java:50)
	at org.openstack4j.connectors.jersey2.HttpCommand.create(HttpCommand.java:45)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:53)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:77)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:41)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:84)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:65)
	at com.gmrt.sunrise.genesis.data.utils.OpenStackClient.auth(OpenStackClient.java:91)
