### ISSUE TITLE
Toggle Enabled State :Modify the user whether to enable the results is to let user disable

### ISSUE THREAD

**Issue by benxiaohai1212** [ContainX/openstack4j#197]
Modify the user whether to enable the results is to let user disable is correct?

User jdoe = os.identity().users().enableUser("userId", true);
jdoe.isEnabled() = false;

Version:2.0.1.SNAPSHOT

**Comment by gondor** [comment]
@benxiaohai1212 Haven't been ignoring you.  Just haven't been able to reproduce this.  All of my deployments are returning true.  What version of OpenStack are you running?

**Comment by benxiaohai1212** [comment]
Recently found where an error is to add a user;The user has been added in it to success. But your background error.I don't know why?
I am using version 2.0.1.
The error information is as follows:
Exception in thread "main" ClientResponseException{message=Conflict occurred attempting to store role - Duplicate Entry, status=409, status-code=CONFLICT}
    at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
    at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
    at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:53)
    at org.openstack4j.connectors.okhttp.HttpResponseImpl.getEntity(HttpResponseImpl.java:66)
    at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:164)
    at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:158)
    at org.openstack4j.openstack.identity.internal.UserServiceImpl.create(UserServiceImpl.java:50)
    at com.chinaops.openstack.TenantTest.main(TenantTest.java:66)


                                                thanks!




At 2015-01-15 13:39:44, "Jeremy Unruh" <notifications@github.com> wrote:


@benxiaohai1212 Haven't been ignoring you. Just haven't been able to reproduce this. All of my deployments are returning true. What version of OpenStack are you running?

¡ª

**Comment by vinodborole** [comment]
@benxiaohai1212 closing this for now, please reopen it if the issue persist
