### ISSUE TITLE
ConnectionException in os.telemetry().meters().list()

### ISSUE THREAD

**Issue by DurdenP** [ContainX/openstack4j#338]
Like in https://github.com/gondor/openstack4j/issues/24, i have followed "OpenStack4j Getting Started" and executed (succesfully) all queries.
But, when i run Telemetry(Ceilometer) API:
```javascript
List<? extends Meter> meters = os.telemetry().meters().list(); 
```
I got an exception:
```javascript
Exception in thread "main" ConnectionException{message=java.net.ConnectException: Connection refused, status=0}
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:58)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:164)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:158)
	at org.openstack4j.openstack.telemetry.internal.MeterServiceImpl.list(MeterServiceImpl.java:33)
	at com.mycompany.openstack4j.Example1.main(Example1.java:43)
Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused
	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:229)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:224)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:656)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:653)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:653)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:388)
	at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:86)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	... 6 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at org.glassfish.jersey.client.HttpUrlConnector._apply(HttpUrlConnector.java:321)
	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:227)
	... 18 more
```

**Comment by gondor** [comment]
I have a feeling your deployment doesn't have Telemetry installed.  Easiest way to tell is to System out the Service Catalog object after authenticating.  You'll see the standard service defined like compute, etc but you'll want to see if telemetry or "metering" is present.  If it's not this is the issue.. if it's there please send me the info.

```java
        System.out.println(os.getAccess().getServiceCatalog());
```

**Comment by vinodborole** [comment]
@DurdenP  please close this if its not an issue anymore
