### ISSUE TITLE
Error reading entity from input stream

### ISSUE THREAD

**Issue by niebloomj** [ContainX/openstack4j#423]
I am getting an error when I try to list sahara clusters or create a sahara cluster. It is an internal error with parsing a date that contains a T apparently. I am running openstack4j 2.0.3 and devstack Kilo

My Code:

Cluster cluster = manager.client
        .sahara()
        .clusters()
        .create(Builders
                .cluster()
                .name("test-cluster19")
                .pluginName("vanilla")
                .hadoopVersion("2.6.0")
                .image(imageId)
                .addNodeGroup(
                        Builders.nodeGroup().name("worker").flavor("1")
                                .addNodeProcess("namenode")
                                .addNodeProcess("resourcemanager")
                                .addNodeProcess("historyserver")
                                .addNodeProcess("oozie")
                                .addNodeProcess("nodemanager").count(1)
                                .build())
                .addNodeGroup(
                        Builders.nodeGroup().name("worker2")
                                .flavor("1").addNodeProcess("datanode")
                                .count(3).build())
                // .keypairName("mykeypair")
                // .managementNetworkId("")
                .build());

The exception:

Exception in thread "main" javax.ws.rs.ProcessingException: Error reading entity from input stream.
    at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:866)
    at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:783)
    at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
    at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:111)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:399)
    at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:108)
    at org.openstack4j.connectors.jersey2.HttpResponseImpl.readEntity(HttpResponseImpl.java:112)
    at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:56)
    at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:19)
    at org.openstack4j.connectors.jersey2.HttpResponseImpl.getEntity(HttpResponseImpl.java:62)
    at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:169)
    at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:163)
    at org.openstack4j.openstack.sahara.internal.ClusterServiceImpl.list(ClusterServiceImpl.java:31)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to parse Date value '2015-07-14T18:01:09' (format: "yyyy-MM-dd HH:mm:ss"): Unparseable date: "2015-07-14T18:01:09" (through reference chain: org.openstack4j.openstack.sahara.domain.Clusters["clusters"]->org.openstack4j.openstack.sahara.domain.SaharaCluster["updated_at"])
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1415)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:244)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:232)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:206)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
    at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:106)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
    at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1232)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:676)
    at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:777)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:229)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:149)
    at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1124)
    at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:851)
    ... 16 more
Caused by: java.lang.IllegalArgumentException: Failed to parse Date value '2015-07-14T18:01:09' (format: "yyyy-MM-dd HH:mm:ss"): Unparseable date: "2015-07-14T18:01:09"
    at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:159)
    at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:262)
    at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:246)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
    at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:106)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
    ... 32 more

**Comment by ekasitk** [comment]
This is the same issue with #432. Please test my fixed version before I commit the changes.

**Comment by auhlig** [comment]
Merged the fix. Can you close this issue @niebloomj?
