### ISSUE TITLE
Sahara response date-time stamps cause exception

### ISSUE THREAD

**Issue by bgombert** [ContainX/openstack4j#432]
It appears that the opensatck4j support for Data Processing(sahara) has an issue with rest api responses that contain a date-time stamp (example below). Debugging was turned on and the cluster creation is successful however the databinding of the response fails. It seems that the openstack sahara service uses a different format for datetime stamps. Seems that the datetime stamps may not be ISO 8601 conformant. Debugging api calls to nova shows datetime stamps that are ISO 8601 conformant.

Have others had success using the openstack4j sahara api? If so what version of openstack are you using?

openstack envirnment:
            devstack kilo with sahara enabled

pom contains:
              dependency for openstack4j version 2.0.4, withdeps

java code for cluster creation:
    Cluster cluster = os.sahara().clusters().create(Builders.cluster()
                                 .name("vanilla-cluster").pluginName("vanilla").hadoopVersion("1.2.1")
                                 .template("cb6b597c-6a6c-4186-8c1b-a6db0419ed56")
                                 .image("8cf7eb97-ae07-45a6-a73f-322dd839972b")
                                 .keypairName("mykey").build());

Jul 21, 2015 4:18:48 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 \* Sending client request on thread main
1 > POST http://1.1.1.1:8386/v1.1/1c9e77bd7f5146eaaf64bf1ed053b73d/clusters
1 > Accept: application/json
1 > Content-Type: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
1 > X-Auth-Token: 4d640e13f6844cabb5ea5b4bed3b9556
{
  "name" : "vanilla-cluster",
  "cluster_template_id" : "cb6b597c-6a6e-4186-8c1a-a6db0419ed56",
  "default_image_id" : "8cf7eb07-ae07-4596-a73f-322dd839972b",
  "user_keypair_id" : "barry",
  "plugin_name" : "vanilla",
  "hadoop_version" : "1.2.1"
}

Jul 21, 2015 4:18:50 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 \* Client response received on thread main
2 < 202
2 < Connection: keep-alive
2 < Content-Length: 2510
2 < Content-Type: application/json
2 < Date: Tue, 21 Jul 2015 20:14:52 GMT
2 < X-Openstack-Request-Id: req-c872e1ad-f355-4c0e-892a-1d1c70f00311
{"cluster": {"provision_progress": [], "user_keypair_id": "barry", "updated_at": "2015-07-21T20:14:51", "is_transient": false, "node_groups": [{"volume_local_to_instance": false, "availability_zone": "", "updated_at": "2015-07-21T20:14:51", "instances": [], "node_group_template_id": "9506ff3f-ff3e-4027-9870-93dfa0d12d5e", "volumes_per_node": 0, "id": "a2bc7a73-3cb1-4d9c-93cc-3c71573973d5", "security_groups": [], "node_configs": {"HDFS": {}, "JobFlow": {}, "MapReduce": {}, "Hive": {}}, "auto_security_group": true, "volumes_availability_zone": null, "volume_mount_prefix": "/volumes/disk", "floating_ip_pool": "", "image_id": null, "volumes_size": 0, "is_proxy_gateway": false, "count": 1, "name": "vMt", "created_at": "2015-07-21T20:14:51", "volume_type": null, "node_processes": ["namenode", "jobtracker"], "flavor_id": "2"}, {"volume_local_to_instance": false, "availability_zone": "", "updated_at": "2015-07-21T20:14:51", "instances": [], "node_group_template_id": "d2e1acdc-7683-4c4f-a47f-2eb05b7e898a", "volumes_per_node": 0, "id": "cfc3d590-74b9-49c2-a1a8-1c3847f8c6c8", "security_groups": [], "node_configs": {"HDFS": {}, "JobFlow": {}, "MapReduce": {}, "Hive": {}}, "auto_security_group": true, "volumes_availability_zone": null, "volume_mount_prefix": "/volumes/disk", "floating_ip_pool": "", "image_id": null, "volumes_size": 0, "is_proxy_gateway": false, "count": 1, "name": "vWt", "created_at": "2015-07-21T20:14:51", "volume_type": null, "node_processes": ["datanode", "tasktracker"], "flavor_id": "2"}], "management_public_key": "ssh-rsa AAABB3NzaC1yc2EAAAADAQABAAABAQCb3iSOrxgj1cdBsZVLaEvVMbstWFbBr+kRanLZuj9S3gOozEKUz8ZVkai39ibKaa4YamhCwJjvOYTySqT6rLDAjErCMlhxOn2DTX/U0I9Rv50butGtRwwKnLnXWFdaUwOEmGL98W/RiMqLEEhlAHTaU9gqiKDJxNcqbYBMoFTkgya7W9q7Hhv6nf2LylGi/BktnrF+O8EMSh4cbIWgOEWUwn45FmfTCje0sQOQHfV8wkHgpzoYAgBVSp3jXeXKZRdippe0M6/tefMLetVH2ThwXO8qiLaAnG5rlzMtDRedO0E8PkcRHo6rg3WbG//chAirCmYVyTXnXLNNNAmoVgX7 Generated by Sahara\n", "id": "01338c8a-f904-414d-a665-96eafa6d11ee", "trust_id": null, "cluster_configs": {"HDFS": {}, "MapReduce": {}, "general": {}}, "default_image_id": "8cf7eb07-ae07-4596-a73f-322dd839972b", "status": "Validating", "neutron_management_network": null, "description": "", "plugin_name": "vanilla", "anti_affinity": [], "status_description": "", "hadoop_version": "1.2.1", "info": {}, "cluster_template_id": "cb6b597c-6a6e-4186-8c1a-a6db0419ed56", "name": "vanilla-cluster", "tenant_id": "1c9b77bd7f5146ebaf64bf1ed053b73d", "created_at": "2015-07-21T20:14:51"}}

Exception in thread "main" javax.ws.rs.ProcessingException: Error reading entity from input stream.
       at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:866)
       at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:783)
       at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
       at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:111)
       at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
       at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
       at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:399)
       at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:108)
       at org.openstack4j.connectors.jersey2.HttpResponseImpl.readEntity(HttpResponseImpl.java:112)
       at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:56)
       at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:19)
       at org.openstack4j.connectors.jersey2.HttpResponseImpl.getEntity(HttpResponseImpl.java:62)
       at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:169)
       at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:163)
       at org.openstack4j.openstack.sahara.internal.ClusterServiceImpl.create(ClusterServiceImpl.java:50)
       at com.parc.bdf.openstackapp.SaharaDemoApp.main(SaharaDemoApp.java:90)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to parse Date value '2015-07-21T20:14:51' (format: "yyyy-MM-dd HH:mm:ss"): Unparseable date: "2015-07-21T20:14:51" (through reference chain: org.openstack4j.openstack.sahara.domain.SaharaCluster["updated_at"])
       at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
       at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
       at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1415)
       at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:244)
       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
       at com.fasterxml.jackson.databind.ObjectReader._unwrapAndDeserialize(ObjectReader.java:1443)
       at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1229)
       at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:676)
       at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:777)
       at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
       at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:229)
       at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:149)
       at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1124)
       at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:851)
       ... 16 more
Caused by: java.lang.IllegalArgumentException: Failed to parse Date value '2015-07-21T20:14:51' (format: "yyyy-MM-dd HH:mm:ss"): Unparseable date: "2015-07-21T20:14:51"
       at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:159)
       at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:262)
       at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:246)
       at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
       at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:106)
       at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
       ... 26 more

**Comment by ekasitk** [comment]
I'm using Sahara Juno version. It appears that the date format has recently been changed into ISO 8601 (https://github.com/openstack/sahara/commit/3b4f17bc18c34ae4c7ec37e9d4dff41a32abdc28). Could you test the fixed version on my repo https://github.com/ekasitk/openstack4j/tree/sahara?

**Comment by auhlig** [comment]
Merged the fix. Can you close this issue @bgombert?
