### ISSUE TITLE
Keystone V3 error when getting users or project list with a admin role user, Openstack4j version 2.0.5

### ISSUE THREAD

**Issue by markleecom** [ContainX/openstack4j#477]
My openstack version is kilo, and I can get users list or project list correctly using keystone V2. Mainly code is: 
os = OSFactory.builder().endpoint(tokenUrl)
				.credentials(userName,password)
				.authenticate();
UserService userService = os.identity().users();
List<? extends User> users = userService.list();

But when using keystone V3,  the code is:
Identifier domainId = Identifier.byId("default");
		os = OSFactory.builderV3().endpoint(tokenUrl)
				.credentials(userName, password,domainId)
				.authenticate();
I got this exception :
Exception in thread "main" java.lang.NullPointerException
	at org.openstack4j.openstack.identity.internal.DefaultEndpointURLResolver.resolveV3(DefaultEndpointURLResolver.java:110)
	at org.openstack4j.openstack.identity.internal.DefaultEndpointURLResolver.findURL(DefaultEndpointURLResolver.java:50)
	at org.openstack4j.openstack.internal.OSClientSession.getEndpoint(OSClientSession.java:202)
	at org.openstack4j.core.transport.HttpRequest$RequestBuilder.build(HttpRequest.java:405)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:177)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:172)
	at org.openstack4j.openstack.identity.internal.UserServiceImpl.list(UserServiceImpl.java:25)
	at com.cloudmap.csmc.kernel.cloud.openstack_v3_kilo.util.Openstack4jUtil.authenticated(Openstack4jUtil.java:57)
	at com.cloudmap.csmc.kernel.cloud.openstack_v3_kilo.util.Openstack4jUtil.main(Openstack4jUtil.java:114)

I can get the correct user list or project list with keystone v3, using openstack REST API.

**Comment by mazimo** [comment]
As far as I can tell, OpenStack4J only supports keystone v3 authentication and not other v3 operations. The comment in DefaultEndPointURLResolver seems to confirm this: https://github.com/gondor/openstack4j/search?utf8=%E2%9C%93&q=only+support+V3&type=Code

**Comment by markleecom** [comment]
Ok, thank you.

**Comment by vinodborole** [comment]
@markleecom please reopen if this issue still exists for u
