### ISSUE TITLE
NPE creating image from response headers using http-connector

### ISSUE THREAD

**Issue by olivergondza** [ContainX/openstack4j#635]
Exception[1] is thrown when parsing response[2] using openstack4j-http-connector:2.0.9. The problem seems to be there is a phony header `null=HTTP/1.1 200 OK` on https://github.com/gondor/openstack4j/blob/6f86b6b/core/src/main/java/org/openstack4j/openstack/image/domain/functions/ImageFromHeadersFunction.java#L83. The problem does not appear when `openstack4j-httpclient` used.

[1]
```
java.lang.NullPointerException
	at org.openstack4j.openstack.image.domain.functions.ImageFromHeadersFunction.apply(ImageFromHeadersFunction.java:87)
	at org.openstack4j.openstack.image.domain.functions.ImageFromHeadersFunction.apply(ImageFromHeadersFunction.java:45)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:54)
	at org.openstack4j.connectors.http.HttpResponseImpl.getEntity(HttpResponseImpl.java:73)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:189)
	at org.openstack4j.openstack.image.internal.ImageServiceImpl.get(ImageServiceImpl.java:100)
```

[2]
```
HEAD /v1/images/IMAGEID HTTP/1.1
Content-Type: application/json
Accept: application/json; charset=utf-8
User-Agent: OpenStack4j / OpenStack Client
X-Auth-Token: XAUTHTOKEN
Host: OPENSTACK:9292
Connection: keep-alive


HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Content-Length: 0
X-Image-Meta-Property-Instance_type_memory_mb: 8192
X-Image-Meta-Status: queued
X-Image-Meta-Property-Central_ci: yes
X-Image-Meta-Owner: 9ef4d9c5b208431abc45bd2535389725
X-Image-Meta-Name: test
X-Image-Meta-Created_at: 2016-04-19T10:41:26
X-Image-Meta-Container_format: bare
X-Image-Meta-Property-Image_type: snapshot
X-Image-Meta-Property-Os_distro: rhel
X-Image-Meta-Property-Instance_type_root_gb: 80
X-Image-Meta-Min_ram: 0
X-Image-Meta-Updated_at: 2016-04-19T10:41:26
X-Image-Meta-Property-Instance_type_rxtx_factor: 1
X-Image-Meta-Id: IMAGEID
X-Image-Meta-Property-Instance_type_id: 3
X-Image-Meta-Property-Os_type: linux
X-Image-Meta-Property-Instance_uuid: 44ee9e1d-a593-452c-99c1-2d1f5dc93183
X-Image-Meta-Property-Instance_type_vcpus: 4
X-Image-Meta-Property-Architecture: x86_64
X-Image-Meta-Property-Instance_type_name: m1.large
X-Image-Meta-Property-Instance_type_flavorid: 4
X-Image-Meta-Property-Instance_type_ephemeral_gb: 0
X-Image-Meta-Property-Os_version: 6.7
X-Image-Meta-Deleted: False
X-Image-Meta-Property-Instance_type_swap: 0
X-Image-Meta-Protected: False
X-Image-Meta-Min_disk: 80
X-Image-Meta-Size: 0
X-Image-Meta-Property-Base_image_ref: 12b6c73d-d3ce-44b5-9342-734176c8e6b6
X-Image-Meta-Is_public: False
X-Image-Meta-Disk_format: qcow2
Location: http://OPENSTACK:9292/v1/images/IMAGEID
X-Openstack-Request-Id: REQUESTID
Date: Tue, 19 Apr 2016 10:41:27 GMT
Connection: keep-alive
```

**Comment by olivergondza** [comment]
This is coming directly from JDK:
```
$ groovy -e 'println new URL("http://github.com/").openConnection().headerFields'
[null:[HTTP/1.1 301 Moved Permanently], Content-length:[0], Location:[https://github.com/], Connection:[close]]
```
