### ISSUE TITLE
some Queries openstack4j after authenticate.

### ISSUE THREAD

**Issue by huytt1992** [ContainX/openstack4j#650]
here my code.
package com.inet.dms.openstack4j;

import java.util.List;

import org.openstack4j.api.OSClient;
import org.openstack4j.model.common.Identifier;
import org.openstack4j.model.compute.Action;
import org.openstack4j.model.compute.Flavor;
import org.openstack4j.model.compute.Server;
import org.openstack4j.model.identity.Tenant;
import org.openstack4j.model.identity.User;
import org.openstack4j.openstack.OSFactory;

public class OpenStackProvisioning {

```
public static void main(String[] args) {
    // TODO Auto-generated method stub

    try {

        System.out.println("step 01: authenticate");

        OSClient os = OSFactory.builderV3()
                .endpoint("http://10.60.xxx.xxx:5000/v3")
                .credentials("adminxxx", "xxxxx", Identifier.byName("default"))
                .scopeToProject(Identifier.byName("admin"), Identifier.byName("default")).authenticate();

        System.out.println("step 02 :");
        List<? extends User> users = os.identity().users().list();


        List<? extends Tenant> tenants = os.identity().tenants().list();

        // Find all running Servers
        List<? extends Server> servers = os.compute().servers().list(); 

        // Suspend a Server
        os.compute().servers().action("serverId", Action.SUSPEND);

        System.out.println("step 03");
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}
```

}

. this is error print : i was debug , error  in line : List<? extends Server> servers = os.compute().servers().list(); 
step 01: authenticate
step 02 :
ConnectionException{message=controller, status=0}
    at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:60)
    at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:32)
    at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
    at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:189)
    at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:183)
    at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:95)
    at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:80)
    at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:72)
    at com.inet.dms.openstack4j.OpenStackProvisioning.main(OpenStackProvisioning.java:35)
Caused by: java.net.UnknownHostException: controller
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$1.lookupAllHostAddr(Unknown Source)
    at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
    at java.net.InetAddress.getAllByName0(Unknown Source)
    at java.net.InetAddress.getAllByName(Unknown Source)
    at java.net.InetAddress.getAllByName(Unknown Source)
    at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
    at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:102)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    at org.openstack4j.connectors.httpclient.HttpCommand.execute(HttpCommand.java:112)
    at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
    at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
    ... 8 more

please help me, thank you very much

**Comment by dhague** [comment]
The error message is telling you the problem:
> Caused by: java.net.UnknownHostException: controller

The service catalog being returned in the authentication process must have an endpoint for the identity or compute service that has the hostname "controller", and this hostname cannot be resolved from the machine you're running OS4J on.

**Comment by huytt1992** [comment]
thank dhague very much,
I have changed the hostname , ex: ip127.x.x1.  controller in file hosts system
it has been in operation

**Comment by vinodborole** [comment]
@huytt1992  Please close this issue

**Comment by auhlig** [comment]
Closing since there doesn't seem to be an issue in OS4j and this is rather for stackoverflow or the google group.
