### ISSUE TITLE
openstack4j-3.0.0.jar get os error

### ISSUE THREAD

**Issue by benxiaohai1212** [ContainX/openstack4j#717]
<dependency>
  <groupId>org.pacesys</groupId>
  <artifactId>openstack4j</artifactId>
  <version>3.0.0</version>
</dependency>
join pom.xml

OSClientV2 os = OSFactory.builderV2()
				.endpoint("http://xxxxxxxx:5000/v2.0/")
				.credentials("xxx@xxx.com", "1234.com")
				.tenantName("xxxxxx")
				.authenticate();

Exception in thread "main" ConnectionException{message=com.fasterxml.jackson.jaxrs.cfg.EndpointConfigBase.<init>(Lcom/fasterxml/jackson/databind/cfg/MapperConfig;)V, status=0}
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:58)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:122)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:52)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:117)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:1)
	at org.openstack4j.api.compute.server.ServerTest.printServerlist(ServerTest.java:32)
	at org.openstack4j.api.compute.server.ServerTest.main(ServerTest.java:16)
Caused by: javax.ws.rs.ProcessingException: com.fasterxml.jackson.jaxrs.cfg.EndpointConfigBase.<init>(Lcom/fasterxml/jackson/databind/cfg/MapperConfig;)V
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:233)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:656)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:653)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:653)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:413)
	at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:84)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	... 8 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.jaxrs.cfg.EndpointConfigBase.<init>(Lcom/fasterxml/jackson/databind/cfg/MapperConfig;)V
	at com.fasterxml.jackson.jaxrs.json.JsonEndpointConfig.<init>(JsonEndpointConfig.java:30)
	at com.fasterxml.jackson.jaxrs.json.JsonEndpointConfig.forWriting(JsonEndpointConfig.java:45)
	at com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider._configForWriting(JacksonJsonProvider.java:223)
	at com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider._configForWriting(JacksonJsonProvider.java:45)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase._configForWriting(ProviderBase.java:469)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:577)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:263)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1154)
	at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:500)
	at org.glassfish.jersey.client.HttpUrlConnector._apply(HttpUrlConnector.java:315)
	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:227)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:224)
	... 19 more

**Comment by vinodborole** [comment]
@benxiaohai1212 there seems some conflicts with the jackson libraries that get downloaded with jersey2 in your local maven repos, please clean/update your project and check.  

This implementation works fine for me.

**Comment by vinodborole** [comment]
@benxiaohai1212 please reopen if this issue still exists for u
