### ISSUE TITLE
Openstack4j null

### ISSUE THREAD

**Issue by Cookie-Wang** [ContainX/openstack4j#725]
i can use openstack v2 to get server list,but when i use v3 to get server list get error,and i can use rest api to  get server list.
>>>>>>>>>>>>error info:<<<<<<<<<<<<<<<<<<<<
Exception in thread "main" java.lang.NullPointerException
	at org.openstack4j.openstack.identity.internal.DefaultEndpointURLResolver.resolveV3(DefaultEndpointURLResolver.java:120)
	at org.openstack4j.openstack.identity.internal.DefaultEndpointURLResolver.findURLV3(DefaultEndpointURLResolver.java:70)
	at org.openstack4j.openstack.internal.OSClientSession$OSClientSessionV3.getEndpoint(OSClientSession.java:388)
	at org.openstack4j.core.transport.HttpRequest$RequestBuilder.build(HttpRequest.java:405)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:192)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:187)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:74)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:59)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:51)
	at OpenStack4J_V3_Demo.getAllVms(OpenStack4J_V3_Demo.java:41)
	at OpenStack4J_V3_Demo.main(OpenStack4J_V3_Demo.java:17)

>>>>>>>>>>>>1.openstack4j v2 ：identify and get server list code,is：<<<<<<<<<<<<<<<<<<<<
OSClientV2 osClientV2 = OSFactory.builderV2()
				.endpoint("http://192.168.217.100:5000/v2.0")
				.credentials("admin", "root123").tenantName("admin")
				.authenticate();

List<? extends Server> vmList = osClientV2 .compute().servers().list();

>>>>>>>>>>>>2.openstack4j v3 ：identify and get server list code,is：<<<<<<<<<<<<<<<<<<<<
Identifier domainIdentifier = Identifier.byId("default");
		OSClientV3 osClientV3= OSFactory.builderV3()
				.endpoint("http://192.168.217.100:5000/v3")
				.credentials("admin", "root123", domainIdentifier)
				.authenticate();
List<? extends Server> vmList = osClientV3.compute().servers().list();

>>>>>>>>>>>>3.Rest Api v3：identify and get server list ,is：<<<<<<<<<<<<<<<<<<<<
URL:http://192.168.217.100:5000/v3/auth/tokens
Method:POST
Request body:
{
   "auth": {
      "identity": {
         "methods": [
            "password"
         ],
         "password": {
            "user": {
               "domain":{"id":"Default"},
               "name": "admin",
               "password": "root123"
            }
         }
      },
      "scope": {
         "project": {
           "name": "admin",
           "domain":{"id":"Default"}
         }
      }
   }
}

respone body:

"token": {
"methods": [1]
0:  "password"
-
"roles": [1]
0:  {
"id": "a5559b79f54d4021bb92251e0c011c6a"
"name": "admin"
}-
-
"expires_at": "2016-06-21T04:30:47.773123Z"
"project": {
"domain": {
"id": "default"
"name": "Default"
}-
"id": "11c57449dfa94ffda6613e477762f7cd"
"name": "admin"
}-
"catalog": [11]
0:  {
"endpoints": [3]
0:  {
"region_id": "RegionOne"
"url": "http://controller:8777"
"region": "RegionOne"
"interface": "admin"
"id": "93b1711654c948d4968b86da5e212963"
}-
1:  {
"region_id": "RegionOne"
"url": "http://controller:8777"
"region": "RegionOne"
"interface": "internal"
"id": "9c58e3e786ee4cb1988558b8ea95d0b1"
}-
2:  {
"region_id": "RegionOne"
"url": "http://controller:8777"
"region": "RegionOne"
"interface": "public"
"id": "d3e2d7d682c44e7f8d810c229e976d48"
}-
-
"type": "metering"
"id": "01059cec5272437fa4113c1e8cfef869"
"name": "ceilometer"
}-
1:  {
"endpoints": [3]
0:  {
"region_id": "RegionOne"
"url": "http://controller:35357/v2.0"
"region": "RegionOne"
"interface": "admin"
"id": "334a787f233c421e8889e0de7e69c9bf"
}-
1:  {
"region_id": "RegionOne"
"url": "http://controller:5000/v2.0"
"region": "RegionOne"
"interface": "internal"
"id": "815e5a5397d04d8a94875d2f859d92ab"
}-
2:  {
"region_id": "RegionOne"
"url": "http://controller:5000/v2.0"
"region": "RegionOne"
"interface": "public"
"id": "dd9a867d171b4ec883ba67aabdaf9df3"
}-
-
"type": "identity"
"id": "199f4fcbfd1d46149da302c0c95e1d03"
"name": "keystone"
}-
2:  {
"endpoints": [0]
"type": "image"
"id": "5555fbc867dc41feb1c43f3ab9c29796"
"name": "glance"
}-
3:  {
"endpoints": [3]
0:  {
"region_id": "RegionOne"
"url": "http://controller:8776/v2/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "internal"
"id": "37712d877aee4625964442bddf785c4c"
}-
1:  {
"region_id": "RegionOne"
"url": "http://controller:8776/v2/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "public"
"id": "8ed68da39c9e462eacb3569ffe537a98"
}-
2:  {
"region_id": "RegionOne"
"url": "http://controller:8776/v2/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "admin"
"id": "a2b3770b32104214ad56adc979e9754a"
}-
-
"type": "volume"
"id": "75595046d5314fa482db039dee0f2d8b"
"name": "cinder"
}-
4:  {
"endpoints": [3]
0:  {
"region_id": "RegionOne"
"url": "http://controller:8004/v1/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "public"
"id": "106529f0c63940abb2422e5277e590ff"
}-
1:  {
"region_id": "RegionOne"
"url": "http://controller:8004/v1/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "admin"
"id": "d4665575cb2f4b349e2c024728e29f05"
}-
2:  {
"region_id": "RegionOne"
"url": "http://controller:8004/v1/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "internal"
"id": "e8a7ca17dd2b474d98ca0e7d310f5a13"
}-
-
"type": "orchestration"
"id": "8aaea6bdc7bc497ca050349d48f09e57"
"name": "heat"
}-
5:  {
"endpoints": [3]
0:  {
"region_id": "RegionOne"
"url": "http://controller:8776/v2/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "public"
"id": "1d3d49f2d2c942a09eddc3b9c5394521"
}-
1:  {
"region_id": "RegionOne"
"url": "http://controller:8776/v2/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "admin"
"id": "365d821e4fd74f9d91ca413faf861ebc"
}-
2:  {
"region_id": "RegionOne"
"url": "http://controller:8776/v2/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "internal"
"id": "b01e2ab120a246188ae5ed6a371d3aab"
}-
-
"type": "volumev2"
"id": "8c55837ab0324a43a607a78828337ff8"
"name": "cinderv2"
}-
6:  {
"endpoints": [3]
0:  {
"region_id": "RegionOne"
"url": "http://controller:8080"
"region": "RegionOne"
"interface": "admin"
"id": "379032b2f6d8431c83737db73153aee1"
}-
1:  {
"region_id": "RegionOne"
"url": "http://controller:8080/v1/AUTH_11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "public"
"id": "7d37a05c13c747ca96bc6fea5f948fc7"
}-
2:  {
"region_id": "RegionOne"
"url": "http://controller:8080/v1/AUTH_11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "internal"
"id": "e29bc1261a404af0adebcb8ba1bd1394"
}-
-
"type": "object-store"
"id": "90b05bce33aa4923bbe17d26f58f8f2a"
"name": "swift"
}-
7:  {
"endpoints": [3]
0:  {
"region_id": "RegionOne"
"url": "http://controller:8774/v2/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "internal"
"id": "13b561dcb82c4b5ca9ddf43123692467"
}-
1:  {
"region_id": "RegionOne"
"url": "http://controller:8774/v2/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "public"
"id": "59fe0cd700724abeb9ec8d126d04ed00"
}-
2:  {
"region_id": "RegionOne"
"url": "http://controller:8774/v2/11c57449dfa94ffda6613e477762f7cd"
"region": "RegionOne"
"interface": "admin"
"id": "8ed152bae94f4965aea93c5e477edf78"
}-
-
"type": "compute"
"id": "a6adc68712f741b8b1d81892a850a470"
"name": "nova"
}-
8:  {
"endpoints": [3]
0:  {
"region_id": "RegionOne"
"url": "http://controller:9292"
"region": "RegionOne"
"interface": "public"
"id": "20396c0c004d42658ad309cf34c671f8"
}-
1:  {
"region_id": "RegionOne"
"url": "http://controller:9292"
"region": "RegionOne"
"interface": "internal"
"id": "b466f758e3554c54ab1e4fcd841aa84a"
}-
2:  {
"region_id": "RegionOne"
"url": "http://controller:9292"
"region": "RegionOne"
"interface": "admin"
"id": "e37d2bbf3dac4fab8c80153a49b74bf4"
}-
-
"type": "image"
"id": "b8830c28af7a4091b29406e17caff8a4"
"name": "glance"
}-
9:  {
"endpoints": [3]
0:  {
"region_id": "RegionOne"
"url": "http://controller:8000/v1"
"region": "RegionOne"
"interface": "public"
"id": "2a0e873ad8db4075a66760dced8605e0"
}-
1:  {
"region_id": "RegionOne"
"url": "http://controller:8000/v1"
"region": "RegionOne"
"interface": "admin"
"id": "49fa62344cf34b88b542bd01081512fe"
}-
2:  {
"region_id": "RegionOne"
"url": "http://controller:8000/v1"
"region": "RegionOne"
"interface": "internal"
"id": "70c14e06dbbc4498af910e2d51f13504"
}-
-
"type": "cloudformation"
"id": "d44c740a1f354892a0dba1c514101067"
"name": "heat-cfn"
}-
10:  {
"endpoints": [3]
0:  {
"region_id": "RegionOne"
"url": "http://controller:9696"
"region": "RegionOne"
"interface": "internal"
"id": "2ba6468b0f284497a144af0003c47b04"
}-
1:  {
"region_id": "RegionOne"
"url": "http://controller:9696"
"region": "RegionOne"
"interface": "admin"
"id": "a850ed64b5f14a0f99f2a58739a037f0"
}-
2:  {
"region_id": "RegionOne"
"url": "http://controller:9696"
"region": "RegionOne"
"interface": "public"
"id": "eecbcf6c3b4f4f1cba4841d29f6b6ca3"
}-
-
"type": "network"
"id": "dd9c33c04c7e49b78712f63e9b3c3c59"
"name": "neutron"
}-
-
"extras": {}
"user": {
"domain": {
"id": "default"
"name": "Default"
}-
"id": "ec00b2a781b243b2be8943559203f405"
"name": "admin"
}-
"audit_ids": [1]
0:  "vt6mfcDaTrah-oDJ5DdkRA"
-
"issued_at": "2016-06-21T03:30:47.773223Z"
}-
}

**Comment by auhlig** [comment]
@Cookie-Wang: Looking at the token's catalog you only configured identity v2 but not v3, which you need to do beforehand.
Sorry for the very late response.

**Comment by vinodborole** [comment]
@Cookie-Wang please close this issue if u are satisfied with the answer
