### ISSUE TITLE
OSAutenticator Null pointer exception when trying to authenticate

### ISSUE THREAD

**Issue by pradeepcsekar** [ContainX/openstack4j#74]
Hi Gondor,

The below snippet, trying to authenticate against the endpoint but throws a null pointer exception as below. Openstack release is icehouse
try
        {

```
     os = OSFactory.builder()
            .endpoint("https://xxxx.com:5000/v2.0/")
            .credentials("user","password")
            .tenantName("name")
            .authenticate();
    }
    catch (Exception e)
    {
        e.printStackTrace();
    }
```

Exception

```
 [java] java.lang.NullPointerException
 [java]     at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:71)
 [java]     at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:38)
 [java]     at org.openstack4j.openstack.OSFactory$OSFactoryBuilder.authenticate(OSFactory.java:150)
 [java]     at bootstrap.OpenstackBootstrap.main(Unknown Source)
 [java] Exception in thread "main" java.lang.NullPointerException
```

What is the issue here?

Thanks

**Comment by vivekmalhotragithub** [comment]
hello,

i can still reproduce it on 2.0.5. This is in my pom.xml

<dependency>
        <groupId>org.pacesys</groupId>
        <artifactId>openstack4j-core</artifactId>
	    <version>2.0.5</version>
    </dependency>
    <dependency>
		  <groupId>org.pacesys.openstack4j.connectors</groupId>
		  <artifactId>openstack4j-jersey2-jdk16</artifactId>
		  <version>2.0.5</version>
	</dependency>


This is the stack trace:

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: ConnectionException{message=Error during execution: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl, status=0}
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:39)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:97)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:48)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:107)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:71)
	at com.nagarro.vivek.openstack.sampleapp.OpenStack4JSample.<clinit>(OpenStack4JSample.java:22)
