### ISSUE TITLE
NullPointerException in org.openstack4j.openstack.networking.domain.NeutronNetwork

### ISSUE THREAD

**Issue by elementc** [ContainX/openstack4j#75]
In recent builds of openstack4j, the following code yields an exception which prevents us from creating a Network.

The code:

``` java
package edu.fit.icis.openstack4jtester;
import org.openstack4j.api.Builders;
import org.openstack4j.api.OSClient;
import org.openstack4j.model.network.Network;
import org.openstack4j.openstack.OSFactory;
import java.util.Date;

public class Main {

    public static void main(String[] args) {
        System.out.println("Getting ready to run the testbed builder...");
        Network built = Builders.network().name("mytestbed").adminStateUp(true).build();
        System.out.println("Ran the command. Got back:");
        System.out.println(built);
        System.out.println("Getting ready to run the testbed create function...");
        Network n = getos().networking().network().create(built);
        System.out.println("Ran the command. Got back:");
        System.out.println(n);
    }

    protected static OSClient getos() {
        if(_os == null || _os.getToken().getExpires().before(new Date())) {
            _os = OSFactory.builder().useNonStrictSSLClient(true).endpoint(_apiEndpoint).tenantName(_user)
                    .credentials(_user, _password).authenticate();
        }else{
            _os = OSFactory.clientFromAccess(_os.getAccess());
        }
        return _os;
    }

    private  static OSClient _os = null;
    protected static String _apiEndpoint;
    protected static String _user;
    protected static String _password;
}
```

The output:

```
Getting ready to run the testbed builder...
Ran the command. Got back:
NeutronNetwork{name=mytestbed, adminStateUp=true, router:external=false, shared=false}
Getting ready to run the testbed create function...
Exception in thread "main" ConnectionException{message=com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.openstack4j.openstack.networking.domain.NeutronNetwork["neutronSubnets"]), status=0}
    at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:59)
    at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
    at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:44)
    at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:136)
    at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:131)
    at org.openstack4j.openstack.networking.internal.NetworkServiceImpl.create(NetworkServiceImpl.java:45)
    at edu.fit.icis.openstack4jtester.Main.main(Main.java:17)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.openstack4j.openstack.networking.domain.NeutronNetwork["neutronSubnets"])
    at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:229)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:224)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:656)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:653)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:653)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:413)
    at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:71)
    at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:66)
    at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:57)
    ... 11 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.openstack4j.openstack.networking.domain.NeutronNetwork["neutronSubnets"])
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
    at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:187)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:647)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
    at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:602)
    at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:635)
    at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:263)
    at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
    at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
    at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1154)
    at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:500)
    at org.glassfish.jersey.client.HttpUrlConnector._apply(HttpUrlConnector.java:315)
    at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:227)
    ... 23 more
Caused by: java.lang.NullPointerException
    at org.openstack4j.openstack.networking.domain.NeutronNetwork.getNeutronSubnets(NeutronNetwork.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:466)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
    ... 34 more

Process finished with exit code 1
```

The change that introduced this error was sometime between builds of 1.0.2-SNAPSHOT. I'm currently trying to isolate the change myself, but figured I'd post what I'm starting with right now.

**Comment by preetammshetty** [comment]
SwiftAccount sa = os.objectStorage().account().get();

throws NullPointerException:

Exception in thread "main" java.lang.NullPointerException
	at org.openstack4j.openstack.identity.internal.DefaultEndpointURLResolver.resolveV3(DefaultEndpointURLResolver.java:110)
	at org.openstack4j.openstack.identity.internal.DefaultEndpointURLResolver.findURL(DefaultEndpointURLResolver.java:50)
	at org.openstack4j.openstack.internal.OSClientSession.getEndpoint(OSClientSession.java:202)
	at org.openstack4j.core.transport.HttpRequest$RequestBuilder.build(HttpRequest.java:405)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.executeWithResponse(BaseOpenStackService.java:182)
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageAccountServiceImpl.get(ObjectStorageAccountServiceImpl.java:27)
	at hello.test.FirstClass.main(FirstClass.java:16)
