### ISSUE TITLE
Image service api throws exception when doing concurrent access

### ISSUE THREAD

**Issue by dennischen** [ContainX/openstack4j#754]
Hi
When doing my project's large vm creation concurrently. I got this error.
> 16:08:18,485 ERROR [my.Test] (EJB default - 10) For input string: "": java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) [rt.jar:1.7.0_55]
	at java.lang.Long.parseLong(Long.java:453) [rt.jar:1.7.0_55]
	at java.lang.Long.parseLong(Long.java:483) [rt.jar:1.7.0_55]
	at java.text.DigitList.getLong(DigitList.java:194) [rt.jar:1.7.0_55]
	at java.text.DecimalFormat.parse(DecimalFormat.java:1316) [rt.jar:1.7.0_55]
	at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:1793) [rt.jar:1.7.0_55]
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1455) [rt.jar:1.7.0_55]
	at com.fasterxml.jackson.databind.util.StdDateFormat.parseAsISO8601(StdDateFormat.java:436) [jackson-databind-2.4.1.3.jar:2.4.1.3]
	at com.fasterxml.jackson.databind.util.StdDateFormat.parse(StdDateFormat.java:283) [jackson-databind-2.4.1.3.jar:2.4.1.3]
	at com.fasterxml.jackson.databind.util.StdDateFormat.parse(StdDateFormat.java:259) [jackson-databind-2.4.1.3.jar:2.4.1.3]
	at org.openstack4j.openstack.internal.Parser.asDate(Parser.java:73) [openstack4j-core-2.0.5.1.YZ-rc.jar:]
	at org.openstack4j.openstack.image.domain.functions.ImageFromHeadersFunction.apply(ImageFromHeadersFunction.java:72) [openstack4j-core-2.0.5.1.YZ-rc.jar:]
	at org.openstack4j.openstack.image.domain.functions.ImageFromHeadersFunction.apply(ImageFromHeadersFunction.java:45) [openstack4j-core-2.0.5.1.YZ-rc.jar:]
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:49) [openstack4j-core-2.0.5.1.YZ-rc.jar:]
	at org.openstack4j.connectors.httpclient.HttpResponseImpl.getEntity(HttpResponseImpl.java:72) [openstack4j-httpclient-2.0.5.1.YZ-rc.jar:]
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:184) [openstack4j-core-2.0.5.1.YZ-rc.jar:]
	at org.openstack4j.openstack.image.internal.ImageServiceImpl.get(ImageServiceImpl.java:98) [openstack4j-core-2.0.5.1.YZ-rc.jar:]

If you read Parser.java, it uses static StdDateFormat.instance and SimpleDateFormat, but that are not thread safe. 
I saw some of them are protected by synchronized (safer but locked) but some are not.
Concurrently access to a SimpleDateFormat might cause many kind of error(http://stackoverflow.com/questions/4021151/java-dateformat-is-not-threadsafe-what-does-this-leads-to)

**Comment by vinodborole** [comment]
@gondor @auhlig any comments on this?
