### ISSUE TITLE
Unsupported major.minor version 52.0 

### ISSUE THREAD

**Issue by liuxiaobingbj** [ContainX/openstack4j#760]
Caused by: java.lang.UnsupportedClassVersionError: org/openstack4j/api/exceptions/ClientResponseException : Unsupported major.minor version 52.0 (unable to load class org.openstack4j.api.exceptions.ClientResponseException)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2961)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1210)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1690)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2404)
	at java.lang.Class.getDeclaredConstructors(Class.java:1853)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:231)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1002)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:975)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:198)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:444)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:418)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:546)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:150)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:303)
	... 23 more

**Comment by vinodborole** [comment]
@liuxiaobingbj Please check the java version you are using o4j needs 1.7

**Comment by liuxiaobingbj** [comment]
Before I use is 1.7,   1.8 is not the problem,  but create a flavor is wrong. :
ClientResponseException{message=Invalid input for field/attribute flavor. Value: {u'name': u'1vCpu/1024GMemory/50GDisk', u'ram': 1024, u'OS-FLV-DISABLED:disabled': False, u'vcpus': 1, u'swap': 512, u'os-flavor-access:is_public': False, u'rxtx_factor': 1.2, u'OS-FLV-EXT-DATA:ephemeral': 0, u'disk': 50, u'public': False}. Additional properties are not allowed (u'OS-FLV-DISABLED:disabled', u'public' were unexpected), status=400, status-code=BAD_REQUEST}

**Comment by vinodborole** [comment]
@liuxiaobingbj  please look at #573

**Comment by vinodborole** [comment]
@liuxiaobingbj  please close this if you are satisfied
