### ISSUE TITLE
Occasionally receiving "IllegalStateException: Already connected" exception for SSL connections

### ISSUE THREAD

**Issue by smcallister** [ContainX/openstack4j#78]
We are currently using the 1.0.2 build of Openstack4j and connecting to an HTTPS endpoint.  Occasionally we are seeing the following error while trying to authenticate to OpenStack:

java.util.concurrent.ExecutionException: ConnectionException{message=Already connected, status=0}
        at org.openstack4j.core.transport.internal.HttpExecutor.invoke(HttpExecutor.java:149)
        at org.openstack4j.core.transport.internal.HttpExecutor.invoke(HttpExecutor.java:116)
        at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:79)
        at org.openstack4j.openstack.OSFactory$OSFactoryBuilder.authenticate(OSFactory.java:201)
Caused by: javax.ws.rs.ProcessingException: Already connected
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:224)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:634)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:631)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:421)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:631)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:391)
        at org.openstack4j.core.transport.internal.HttpExecutor.invoke(HttpExecutor.java:142)
        ... 9 more
Caused by: java.lang.IllegalStateException: Already connected
        at sun.net.www.protocol.http.HttpURLConnection.setRequestProperty(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.setRequestProperty(Unknown Source)
        at org.glassfish.jersey.client.HttpUrlConnector.writeOutBoundHeaders(HttpUrlConnector.java:309)
        at org.glassfish.jersey.client.HttpUrlConnector.access$100(HttpUrlConnector.java:81)
        at org.glassfish.jersey.client.HttpUrlConnector$3.getOutputStream(HttpUrlConnector.java:283)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:198)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:192)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:260)
        at org.glassfish.jersey.message.internal.OutboundMessageContext.commitStream(OutboundMessageContext.java:822)
        at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:451)
        at org.glassfish.jersey.client.HttpUrlConnector._apply(HttpUrlConnector.java:287)
        at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:200)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:215)

Has anyone seen something like this before?  I'm not sure if this is related to OpenStack4j, a problem with our environment, or even a bug in Jersey.

**Comment by issamo12** [comment]
please, even when i red the documentation i can't change the default connector from Jersey to okhttp or resteasy, please i'm not a maven user, can you guide me to do it ?

**Comment by gondor** [comment]
Please post what you have in your current project POM as far as OpenStack4j declarations
