### ISSUE TITLE
I have problems when deploy Application in another server.

### ISSUE THREAD

**Issue by huytt1992** [ContainX/openstack4j#824]
i have Application,It is working very stable in Server, and deploy in environment setup WebLogic.
now, i want to change to another server, but  I was having problems and error details:

13:47:59,464 | INFO  | LoggingFilter(102):doFilterHttp | 10.10.10.1 | 123.25.21.12 | nvtm | 
javax.servlet.ServletException: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/glassfish/jersey/client/ClientConfig
      at com.inet.framework.web.filter.ExportFilter.doFilter(ExportFilter.java:70)
      at com.inet.framework.security.authentication.InetAuthenticationProcessingFilter.doFilterHttp(InetAuthenticationProcessingFilter.java:77)
      at com.inet.framework.web.filter.LoggingFilter.doFilterHttp(LoggingFilter.java:91)
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/glassfish/jersey/client/ClientConfig
      at com.inet.dms.provisioning.OpenStack2Provisioning.<init>(OpenStack2Provisioning.java:132)
      at com.inet.dms.service.VPSServiceImpl.getListImage(VPSServiceImpl.java:2664)
      at com.inet.dms.base.BusinessInterceptor.invoke(BusinessInterceptor.java:99)
      at com.inet.framework.base.LoggingInterceptor.invoke(LoggingInterceptor.java:62)
      at com.inet.framework.security.authorization.InetMethodSecurityInterceptor.invoke(InetMethodSecurityInterceptor.java:25)
      at com.inet.framework.security.authorization.InetMethodSecurityInterceptor.invoke(InetMethodSecurityInterceptor.java:25)
      at com.inet.dms.web.action.VPSAction.list(VPSAction.java:99)
      ... 51 more
Caused by: java.lang.NoClassDefFoundError: org/glassfish/jersey/client/ClientConfig
      ... 148 more

I using Lib,
 <dependency>
            <groupId>org.pacesys.openstack4j.connectors</groupId>
            <artifactId>openstack4j-jersey2</artifactId>
            <version>2.20</version>
        </dependency>

if i replace lib openstack4j-jersey2 to  
<dependency>
            <groupId>org.pacesys.openstack4j.connectors</groupId>
            <artifactId>openstack4j-jersey2</artifactId>
            <version>3.0.0</version>
        </dependency>

this problems have been resolved.
Please tell me why the problems cause?
I don't want to change Lib?
thank you so much!

**Comment by vinodborole** [comment]
There probably is a conflict of jars from your existing project.
