### ISSUE TITLE
TestNG      No OpenStack4j connector

### ISSUE THREAD

**Issue by eryeru** [ContainX/openstack4j#832]
when i run a testng class in intellij ,but there is always thow the error:
org.openstack4j.api.exceptions.ConnectorNotFoundException: No OpenStack4j connector found in classpath

	at org.openstack4j.core.transport.internal.HttpExecutor.service(HttpExecutor.java:33)
	at org.openstack4j.core.transport.internal.HttpExecutor.getExecutorName(HttpExecutor.java:43)
	at org.openstack4j.api.AbstractTest.startServer(AbstractTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)

how can i do it?

**Comment by auhlig** [comment]
@eryeru Isn't this question rather for stackoverflow than for an issue?

**Comment by eryeru** [comment]
@auhlig Thank you ! But i solve it,it's intellij setting issue. In the RUN/DEBUG menu ,it must choice the "Use classpath of module",example of "openstack4j-jersey2".

**Comment by mupengyun** [comment]
I also had met the problem like yours，how to choice "Use classpath of module",example of "openstack4j-jersey2" ?

**Comment by mupengyun** [comment]
I solve it. @eryeru Thank you.
