### ISSUE TITLE
version 3.0.2 create OSClientV2 then invokes api throw ConnectionException

### ISSUE THREAD

**Issue by caozhiping123456** [ContainX/openstack4j#845]
this is my code:
OSClientV2 os = OSFactory.builderV2()
                     .endpoint("http://10.254.10.56:5000/v2.0")
	            .credentials("admin", "123456")
	            .tenantName("admin")
	            .authenticate();
List<? extends Subnet> subnets = os.networking().subnet().list();
error message：
Exception in thread "main" ConnectionException{message=URI does not specify a valid host name: http:/v2.0/subnets, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:193)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:187)
	at org.openstack4j.openstack.networking.internal.SubnetServiceImpl.list(SubnetServiceImpl.java:26)
	at sfsf.test.main(test.java:20)
Caused by: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:/v2.0/subnets
	at org.apache.http.impl.client.AbstractHttpClient.determineTarget(AbstractHttpClient.java:766)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:182)
	at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:438)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:688)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:694)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:65)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:61)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:54)
	... 6 more

**Comment by caozhiping123456** [comment]
<dependency>
  <groupId>org.pacesys</groupId>
  <artifactId>openstack4j</artifactId>
  <version>3.0.2</version>
  <classifier>withdeps</classifier>
</dependency>

**Comment by babyachievement** [comment]
@caozhiping123456 ,I have also found the problem, when I use org.pacesys openstack4j 3.0.2 withdeps and run my code on a Linux server. But when I execute it on my desktop, it execute successfully. The following is my error message.

```
Exception in thread "main" ConnectionException{message=URI does not specify a valid host name: http:/v2.1/c4c0080e1c7e4badb800872786dd16f7/os-hypervisors/detail, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:193)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:187)
	at org.openstack4j.openstack.compute.internal.ext.HypervisorServiceImpl.list(HypervisorServiceImpl.java:23)
	at com.oneapm.si.App.main(App.java:28)
Caused by: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:/v2.1/c4c0080e1c7e4badb800872786dd16f7/os-hypervisors/detail
	at org.apache.http.impl.client.AbstractHttpClient.determineTarget(AbstractHttpClient.java:766)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:182)
	at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:438)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:688)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:694)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:65)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:61)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:54)
	... 6 more

```

**Comment by caozhiping123456** [comment]
@babyachievement I have solved it,you try this  here is my pom.xml  openstack4j  dependencies.

**Comment by caozhiping123456** [comment]
@babyachievement <dependency>
  <groupId>org.pacesys</groupId>
  <artifactId>openstack4j-core</artifactId>
  <version>3.0.2</version>
</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>mockwebserver</artifactId>
			<version>3.2.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>1.9.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.8</version>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>junit</groupId>
					<artifactId>junit</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
  <groupId>org.pacesys.openstack4j.connectors</groupId>
  <artifactId>openstack4j-jersey2</artifactId>
  <version>3.0.2</version>
</dependency>
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-common</artifactId>
    <version>2.22.2</version>
</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-json-jackson</artifactId>
			<version>2.11</version>
		</dependency>
			<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.7.3</version>
</dependency>

**Comment by caozhiping123456** [comment]
@babyachievement this is all  pom.xml
<dependencies>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-config</artifactId>
			<version>4.0.2.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-web</artifactId>
			<version>4.0.2.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-servlet-api</artifactId>
			<version>8.0.28</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-dbcp2</artifactId>
			<version>2.1.1</version>
		</dependency>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.2</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.36</version>
		</dependency>
				<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.easymock</groupId>
			<artifactId>easymock</artifactId>
			<version>3.4</version>
			<scope>test</scope>
		</dependency>
		<dependency>
		<groupId>org.mybatis</groupId>
		<artifactId>mybatis</artifactId>
		<version>3.3.0</version>
	</dependency>
	<dependency>
		<groupId>org.mybatis</groupId>
		<artifactId>mybatis-spring</artifactId>
		<version>1.2.3</version>
	</dependency>
	<dependency>
		<groupId>org.springframework.security</groupId>
		<artifactId>spring-security-core</artifactId>
		<version>4.0.2.RELEASE</version>
	</dependency>
	<dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-jdbc</artifactId>
		<version>4.1.6.RELEASE</version>
	</dependency>
	<dependency>
		<groupId>org.aspectj</groupId>
		<artifactId>aspectjweaver</artifactId>
		<version>1.8.7</version>
	</dependency>
	
	
<dependency>
  <groupId>org.pacesys</groupId>
  <artifactId>openstack4j-core</artifactId>
  <version>3.0.2</version>
</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>mockwebserver</artifactId>
			<version>3.2.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>1.9.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.8</version>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>junit</groupId>
					<artifactId>junit</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
  <groupId>org.pacesys.openstack4j.connectors</groupId>
  <artifactId>openstack4j-jersey2</artifactId>
  <version>3.0.2</version>
</dependency>
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-common</artifactId>
    <version>2.22.2</version>
</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-json-jackson</artifactId>
			<version>2.11</version>
		</dependency>
			<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.7.3</version>
</dependency>




<dependency>  
    <groupId>org.slf4j</groupId>  
    <artifactId>slf4j-log4j12</artifactId>  
    <version>1.7.2</version>  
</dependency> 


<dependency>
  <groupId>org.glassfish.jersey.containers</groupId>
  <artifactId>jersey-container-servlet-core</artifactId>
  <version>2.22</version>
</dependency>


<dependency>
  <groupId>javax.xml.ws</groupId>
  <artifactId>jaxws-api</artifactId>
  <version>2.1</version>
</dependency>


<dependency>
  <groupId>org.codehaus.jackson</groupId>
  <artifactId>jackson-core-asl</artifactId>
  <version>1.9.12</version>
</dependency>
<dependency>
  <groupId>org.codehaus.jackson</groupId>
  <artifactId>jackson-mapper-asl</artifactId>
  <version>1.9.12</version>
</dependency>
		<dependency>
			<groupId>org.codehaus.jackson</groupId>
			<artifactId>jackson-jaxrs</artifactId>
			<version>1.9.13</version>
		</dependency>

	</dependencies>

**Comment by caozhiping123456** [comment]
sorry,layout is not very good

**Comment by babyachievement** [comment]
@caozhiping123456  Can you tell me the reason?

**Comment by caozhiping123456** [comment]
@babyachievement It might be a version of the conflict  With other driver package
I am not too sure
