### ISSUE TITLE
Dead TCP detection

### ISSUE THREAD

**Issue by porunov** [ContainX/openstack4j#846]
Hello,

I have 2 swift proxy nodes but as I understand OpenStack4j can use only one proxy node and doesn't support HA. So, I installed a keepalived on both proxy nodes and they share the same IP address. The situation is the next:

OpenStack4j connects to the keystone server and gets an endpoint. After that it starts to save objects into swift through the proxy 1. After proxy 1 is crashed proxy 2 assigns an IP address which was on proxy 1. But OpenStack4j gets stuck and can't continue to work after node1 is crashed. It can continue to work only if we reboot the application.

Can we get an error when a TCP is crashed or reconnect to the new node automatically?

Sincerely,
Alexandr

**Comment by porunov** [comment]
Here is my thread dumb:

```
2016-10-11 17:03:31
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode):

"Attach Listener" #20 daemon prio=9 os_prio=0 tid=0x00007f366c001000 nid=0x7fa5 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00007f36b021b800 nid=0x65de runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007f36b020e800 nid=0x65dd waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007f36b020c000 nid=0x65dc waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f36b020a800 nid=0x65db waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f36b0207800 nid=0x65da waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f36b0206000 nid=0x65d9 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f36b01ce000 nid=0x65d8 in Object.wait() [0x00007f367d52e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000def10a18> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000000def10a18> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f36b01cc000 nid=0x65d7 in Object.wait() [0x00007f367d62f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000def185e0> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x00000000def185e0> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x00007f36b0009800 nid=0x65cd runnable [0x00007f36b703f000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000000dd5c3db0> (a java.io.BufferedInputStream)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
	- locked <0x00000000dd5b65e8> (a sun.net.www.protocol.http.HttpURLConnection)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	- locked <0x00000000dd5b65e8> (a sun.net.www.protocol.http.HttpURLConnection)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:394)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
	at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:84)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.executeWithResponse(BaseOpenStackService.java:197)
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageObjectServiceImpl.put(ObjectStorageObjectServiceImpl.java:130)
	at com.fyfine.loader.Application.swiftTest(Application.java:286)
	at com.fyfine.loader.Application.main(Application.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)

"VM Thread" os_prio=0 tid=0x00007f36b01c6800 nid=0x65d6 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f36b001f000 nid=0x65ce runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f36b0020800 nid=0x65cf runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007f36b0022800 nid=0x65d0 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007f36b0024000 nid=0x65d1 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007f36b0026000 nid=0x65d2 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007f36b0027800 nid=0x65d3 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007f36b0029800 nid=0x65d4 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007f36b002b000 nid=0x65d5 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f36b021e800 nid=0x65df waiting on condition 

JNI global references: 43
```

**Comment by auhlig** [comment]
Hi @porunov,
Feel free to submit a PR.

**Comment by porunov** [comment]
I am sorry. What is PR?

Here is my code:
```
        OSClientV3 os = OSFactory.builderV3()
                .endpoint("http://keystone:5000/v3")
                .credentials("swift", "swift", Identifier.byName("default"))
                .scopeToProject(Identifier.byName("service"), Identifier.byName("default"))
                .authenticate();

        for(int i=0;i<10000;i++) {
            try {
                String etag = os.objectStorage().objects().put("container1", "bigobj" + i + "_1", Payloads.create(new ByteArrayInputStream(("Hello " + i).getBytes())));
                System.out.println(etag);
                String etag2 = os.objectStorage().objects().put("container1", "bigobj" + i + "_2", Payloads.create(new ByteArrayInputStream("World!".getBytes())));
                System.out.println(etag2);

                String manifestStr = "[{\"path\": \"/container1/bigobj" + i + "_1\",\"etag\": null,\"size_bytes\": " + ("Hello " + i).getBytes().length + "}," +
                        "{\"path\": \"/container1/bigobj" + i + "_2\",\"etag\": null,\"size_bytes\": " + "World!".getBytes().length + "}]";

                String etag3 = os.objectStorage().objects().put("container1", "bigobj" + i, Payloads.create(new ByteArrayInputStream(manifestStr.getBytes())),
                        ObjectPutOptions.create()
                                .queryParam("multipart-manifest", "put")
                );

                System.out.println("BIGOBJ_" + i + ": " + etag3);
            }catch(Exception e){
                System.out.println(e);
            }
        }
```

**Comment by porunov** [comment]
When the loop is running I shutdown the proxy node to which OSClientV3 has been connected. After that the code stucks for infinity. I don't see any exception.  os.objectStorage().objects().put just locks and waits. It will never be resumed. How to detect such a dead threads? Is it possible to check if this thread is sending data or just was stuck?
