### ISSUE TITLE
Incompatible change in NovaKeypair

### ISSUE THREAD

**Issue by asilgidjian** [ContainX/openstack4j#869]
I am using OpenStack Liberty instance and OpenStack4J 3.0.3-SNAPSHOT, because I need to create a private flavor, which got fixed with:
https://github.com/ContainX/openstack4j/pull/686/files

However my functionality got broken recently and now I cannot generate key pair. The error is as follows:

```
Additional properties are not allowed (u'deleted' was unexpected), status=400, status-code=BAD_REQUEST}
    at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
    at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
    at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:101)
    at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:47)
    at org.openstack4j.connectors.httpclient.HttpResponseImpl.getEntity(HttpResponseImpl.java:67)
    at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:220)
    at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:202)
    at org.openstack4j.openstack.compute.internal.KeypairServiceImpl.create(KeypairServiceImpl.java:54)
```

I think that the issue is caused by the following change:
https://github.com/ContainX/openstack4j/commit/f5c65ff6d3c67adf2cf062a665cf5e5ebb65443f

Would you fix this?

**Comment by auhlig** [comment]
Could you address this @whaon, @tongh-qtl?

**Comment by whaon** [comment]
ok,I'm checking

**Comment by whaon** [comment]
It's OK now.
The openstack creating keypair api doesn't accept a **deleted** status in the request body.But it's OK now.
Feel free to contact me if you have any problems

**Comment by auhlig** [comment]
Thanks @whaon. 
Please close the issue if the fix worked for you @asilgidjian.

**Comment by asilgidjian** [comment]
Thanks, the fix works!
