### ISSUE TITLE
what is version requirements for openstack4j and maven? any other version required? cos i got issue below:

### ISSUE THREAD

**Issue by mongolkim** [ContainX/openstack4j#892]
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openstack4j/openstack/OSFactory : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.pacesys.openstack4j.App.main(App.java:18)

**Comment by mongolkim** [comment]
and i utilized this below: 	
System.out.println(" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ");
    	OSClientV2 os = OSFactory.builderV2()
    	            .endpoint("http://10.50.0.10:5000/v2.0")
    	            .credentials("admin", "ADMIN_PASS")
    	            .tenantName("admin")
    	            .authenticate();

**Comment by vinodborole** [comment]
@mongolkim its the java version problem, u are using an old version of JRE, please use 1.7+

OpenStack4j 3.0.X - Java 7 (JDK 8 preferred)
OpenStack4j 2.0.X - Java 7
