### ISSUE TITLE
get "ConnectionException{message=Already connected, status=0}" in V3 Auth

### ISSUE THREAD

**Issue by daizh** [ContainX/openstack4j#905]
Hi, guys

I can get throught the V3 authentication, but when I do any real operation (create flavor, list images etc.), I get "ConnectionException{message=Already connected, status=0}" error.

My code:
```
Config config = Config.DEFAULT.withSSLContext(UntrustedSSL.getSSLContext());
    OSClient.OSClientV3 os = OSFactory.builderV3()
            .endpoint("http://10.20.0.11:5000/v3")
            .credentials("admin","admin",Identifier.byName("default"))
            .scopeToProject(Identifier.byId("f8e48f7719df4700a87cbd3cf72ec963"))
            .withConfig(config)
            .authenticate();
```
```
 public Flavor createFlavor(){
        Flavor flavor=Builders.flavor()
                .name("unus")
                .ram(512)
                .vcpus(1)
                .disk(5)
                .rxtxFactor(1.2f)
                .build();
crashed=>   flavor=os.compute().flavors().create(flavor);
        logger.info("Flavor created:"+ flavor.toString());
        return flavor;
    }
```

My error log:
```
Exception in thread "main" ConnectionException{message=Already connected, status=0}
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:58)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:208)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:202)
	at org.openstack4j.openstack.compute.internal.FlavorServiceImpl.create(FlavorServiceImpl.java:92)
	at org.cloudbus.cloudsim.examples.custom.OpenstackDemo.createFlavor(OpenstackDemo.java:80)
	at org.cloudbus.cloudsim.examples.custom.OpenstackDemo.main(OpenstackDemo.java:122)
Caused by: javax.ws.rs.ProcessingException: Already connected
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:264)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
	at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:84)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	... 7 more
Caused by: java.lang.IllegalStateException: Already connected
	at sun.net.www.protocol.http.HttpURLConnection.setRequestProperty(HttpURLConnection.java:3000)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.setOutboundHeaders(HttpUrlConnector.java:421)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.access$100(HttpUrlConnector.java:96)
	at org.glassfish.jersey.client.internal.HttpUrlConnector$4.getOutputStream(HttpUrlConnector.java:384)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:200)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:194)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:262)
	at org.glassfish.jersey.message.internal.OutboundMessageContext.commitStream(OutboundMessageContext.java:816)
	at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:545)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:388)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
	... 18 more
```
My maven: 
```
<dependency>
            <groupId>org.pacesys</groupId>
            <artifactId>openstack4j-core</artifactId>
            <version>3.0.3</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.pacesys.openstack4j.connectors/openstack4j-jersey2 -->
        <dependency>
            <groupId>org.pacesys.openstack4j.connectors</groupId>
            <artifactId>openstack4j-jersey2</artifactId>
            <version>3.0.3</version>
        </dependency>
```

Currently, I'm using  **V3 authentication** and **jersey connector** on **Mitaka Openstack**, and encountering the above problem.

Previously, I was using **V2 authentication** and **jersey connector** on a **much older version of Openstack** , and they ran perfectly.

In [this issue post](https://github.com/ContainX/openstack4j/issues/506#issuecomment-158887796), I found the same error:`message=Already connected`. The post suggests to "trust self-signed certificate", and as I do in `Config.DEFAULT.withSSLContext(UntrustedSSL.getSSLContext());` , it dosen't solve the problem.

When I switch openstack connector to **resteasy**, the error is different:
```
Exception in thread "main" ConnectionException{message=URI does not specify a valid host name: http:/v2.1/f8e48f7719df4700a87cbd3cf72ec963/flavors, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:208)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:202)
	at org.openstack4j.openstack.compute.internal.FlavorServiceImpl.create(FlavorServiceImpl.java:92)
	at org.cloudbus.cloudsim.examples.custom.OpenstackDemo.createFlavor(OpenstackDemo.java:80)
	at org.cloudbus.cloudsim.examples.custom.OpenstackDemo.main(OpenstackDemo.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:/v2.1/f8e48f7719df4700a87cbd3cf72ec963/flavors
	at org.apache.http.impl.client.AbstractHttpClient.determineTarget(AbstractHttpClient.java:766)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:182)
	at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:438)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:688)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:694)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:65)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:61)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:54)
	... 12 more
```

Are there something wrong with my authentication method, or maybe my maven dependencies are the cause?
Thanks you!

**Comment by auhlig** [comment]
Authentication looks good.
It complains about an invalid hostname.
The stacktrace shows the uri `http:/v2.1/f8e48f7719df4700a87cbd3cf72ec963/flavors`, in which the fqdn and port are missing. (http://<fqdn>:<port>/<path>)
The initial authentication should return the token, that contains a service catalog. 
This should contain a valid endpoint for compute. Could you check, that's the case?

**Comment by daizh** [comment]
Thanks for replying.

>The initial authentication should return the token, that contains a service catalog.
This should contain a valid endpoint for compute. Could you check, that's the case?

I've checked the catalog, and I found out the "endpoints url" is something like `http://mitaka_control:8774/v2.1/f8e48f7719df4700a87cbd3cf72ec963`. It seems openstack4j.connector dosen't recognize `mitaka_control` as  a valid host.

**Comment by daizh** [comment]
I've solved it. The problem is because my working machine dose not resolve host name `mitaka_control` to any specific IP. After I edit the system hosts file, the problem disappears.
