### ISSUE TITLE
Object Storage: ConnectionException on put

### ISSUE THREAD

**Issue by lsarni** [ContainX/openstack4j#919]
I'm doing this to create a folder (I know there isn't such a a thing as a folder but well):

```
InputStream emptyContent = new ByteArrayInputStream(new byte[0]);
client.objectStorage().objects().put(publicBucket, folderName, Payloads.create(emptyContent), ObjectPutOptions.create().contentType("application/directory"));
```
        
This worked just fine with version 2.20, but since I had to upgrade to 3.0.3 I get a ConnectionException. The message of the exception comes null and this is the stack trace:

```
Exception in thread "main" ConnectionException{status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.executeWithResponse(BaseOpenStackService.java:224)
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageObjectServiceImpl.put(ObjectStorageObjectServiceImpl.java:130)
	at javaapplication3.ExternalProviderBluemix.createFolder(ExternalProviderBluemix.java:112)
	at javaapplication3.ExternalProviderBluemix.<init>(ExternalProviderBluemix.java:70)
	at javaapplication3.JavaApplication3.main(JavaApplication3.java:26)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:886)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:182)
	at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:438)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:688)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:694)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:65)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:61)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:54)
	... 7 more
Caused by: org.apache.http.ProtocolException: Content-Length header already present
	at org.apache.http.protocol.RequestContent.process(RequestContent.java:96)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132)
	at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:166)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:485)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	... 16 more
```

**Comment by auhlig** [comment]
Could you try another connector?

**Comment by lsarni** [comment]
Is there a way of doing this without using maven?

**Comment by auhlig** [comment]
Maybe. I'd recommend the maven way, as described in our docs.

**Comment by lsarni** [comment]
It worked with OKHTTP, thanks
