### ISSUE TITLE
Cannot associate/disassociate floating ip with port in openstackforj v3.0.3

### ISSUE THREAD

**Issue by pstoyanov91** [ContainX/openstack4j#943]
When trying to associate/disassociate floating ip and port i get the following exception:

`Exception in thread "main" ConnectionException{message=could not find writer for content-type application/json type: java.lang.String, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:208)
	at org.openstack4j.openstack.networking.internal.FloatingIPServiceImpl.disassociateFromPort(FloatingIPServiceImpl.java:95)
	at com.mycompany.mavenproject.Application.main(Application.java:30)
Caused by: java.lang.RuntimeException: could not find writer for content-type application/json type: java.lang.String
	at org.jboss.resteasy.client.ClientRequest.writeRequestBody(ClientRequest.java:470)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.writeRequestBodyToOutputStream(ApacheHttpClient4Executor.java:393)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.buildEntity(ApacheHttpClient4Executor.java:360)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.loadHttpMethod(ApacheHttpClient4Executor.java:332)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:180)
	at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:438)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:688)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:694)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:65)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:61)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:54)
	... 5 more`

This problem doesn't appear in v 3.0.0.
Best regards.

**Comment by smarmy** [comment]
I had a similar issue, except it seemed to fail silently. Going back to 3.0.0 seems to work. Don't really have any more info except this piece of code:

```
    public void assignFloatingIp(String pool)
    {
        floatingIp = client.compute().floatingIps().allocateIP(pool);
        client.compute().floatingIps().addFloatingIP(server, floatingIp.getFloatingIpAddress());
    }
```

**Comment by auhlig** [comment]
Hi @pstoyanov91,
Argh resteasy.. See related issues. Should work with another connector.
