### ISSUE TITLE
Parsing error while listing clusters : Failed to parse Date value

### ISSUE THREAD

**Issue by sunayanasarangi** [ContainX/openstack4j#948]
Hallo Team,
I have an apache spark cluster on openstack sahara and I want to use the openstack4j api. I have established a V2 connection. I am able to list flavours, plugins, servers etc. 
But with functions like os.sahara().clusters().list() , os.sahara().clusters().get(clusterId) , os.sahara().nodeGroupTemplates().list(), os.sahara().nodeGroupTemplates().list(), os.sahara().clusterTemplates().list() or os.sahara().clusterTemplates().get(templateId) I am getting a parsing error. Am I missing something ? Any help will be greatly appreciated !!

Below is my code 
public static void main(String[] args) {
		//Creating and authenticating against OpenStack
		OSClientV2 os = OSFactory.builderV2()
				.endpoint("http://asflexsm.informatik.uni-stuttgart.de:5000/v2.0")
				.credentials("sunayana.sarangi", "*******")
				.tenantName("FlexMash")
				.authenticate();
           List<? extends Cluster> clusters = os.sahara().clusters().list();
           System.out.println(clusters);
}

pom.xml has below dependency:
<dependency>
  		<groupId>org.pacesys</groupId>
  		<artifactId>openstack4j</artifactId>
  		<version>3.0.0</version>
  		<classifier>withdeps</classifier>
	</dependency>

Error log: 
Exception in thread "main" javax.ws.rs.ProcessingException: Error reading entity from input stream.
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:889)	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:115)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:267)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:112)
	at org.openstack4j.connectors.jersey2.HttpResponseImpl.readEntity(HttpResponseImpl.java:113)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:66)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:24)
	at org.openstack4j.connectors.jersey2.HttpResponseImpl.getEntity(HttpResponseImpl.java:63)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:193) at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:187) at org.openstack4j.openstack.sahara.internal.ClusterServiceImpl.list(ClusterServiceImpl.java:31)
	at SaharaMain.main(SaharaMain.java:36)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to parse Date value '2017-02-17T04:55:56' (format: "yyyy-MM-dd HH:mm:ss"): Unparseable date: "2017-02-17T04:55:56" (through reference chain: org.openstack4j.openstack.sahara.domain.Clusters["clusters"]->java.util.ArrayList[0]->org.openstack4j.openstack.sahara.domain.SaharaCluster["updated_at"])	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177) at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1474)at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1470)	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912)	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:777)	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
... 17 more
Caused by: java.lang.IllegalArgumentException: Failed to parse Date value '2017-02-17T04:55:56' (format: "yyyy-MM-dd HH:mm:ss"): Unparseable date: "2017-02-17T04:55:56"	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:158)	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:261)	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:245)	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	... 33 more

Thanks Sunayana

**Comment by auhlig** [comment]
Merged the fix. Can you close this issue @sunayanasarangi?

**Comment by sunayanasarangi** [comment]
Thankyou
