### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

### ISSUE THREAD

**Issue by kumarbabu** [ContainX/openstack4j#971]
Hi,

Could you please help me to resolve this issues.
Find following openstack4j V.3.0.2 pom details, which I am using in current project.

```
<dependency>
			<groupId>org.pacesys</groupId>
			<artifactId>openstack4j</artifactId>
			<version>3.0.2</version>
			<classifier>withdeps</classifier>
</dependency>
```

When I execute the following code I am getting Peer Not Authenticated Exception

```
Config withSSLContext = Config.DEFAULT.withSSLContext(SSLContext.getInstance("TLS"));
OSClient client = OSFactory.builderV2().endpoint("https://xxxxxx:5000/v2.0").withConfig(withSSLContext).credentials(USER_ID, PASSWORD).tenantName("admin").authenticate();
```
Full Error Trace:
```
ConnectionException{message=peer not authenticated, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:122)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:52)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:117)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:79)
	at com.ericsson.openstack4j.util.Main.main(Main.java:32)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:397)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:573)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:425)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:182)
	at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:438)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:688)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:694)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:65)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:61)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:54)
	... 7 more

```

Regards,
StackBoy.

**Comment by auhlig** [comment]
Hi @kumarbabu,

**Comment by kumarbabu** [comment]
Hi @auhlig,

Thanks for your reply.
Sorry, I didn't see this fix in latest release. working fine with following settings.

```
SSLContext sc = SSLContext.getInstance("SSL");
sc.init(null, getTrustingManager(), new java.security.SecureRandom());
InetAddress address = InetAddress.getByName(new URL(getEndPointURL()).getHost());

Config config = Config.newConfig().withSSLContext(sc).withEndpointNATResolution(address.getHostAddress()).withHostnameVerifier(NoopHostnameVerifier.INSTANCE).withSSLVerificationDisabled();

OSClientV2 osClient = OSFactory.builderV2().endpoint(getEndPointURL()).credentials(getLoginName(), getLoginPassword()).withConfig(config).tenantName(getTenantName()).authenticate();
```

Regards,
Kumar.

**Comment by perry123456** [comment]
Hi, I had the same problem and it disappeared after switching to the Apache httpComponents connector. So it might be related to Jersey. CU
