### ISSUE TITLE
NPE when i list projects

### ISSUE THREAD

**Issue by SevenLin** [ContainX/openstack4j#977]
hello,when i use openstak4j(3.0.2) to list projects from my openstack ,i got a npe:

`
java.lang.NullPointerException
	at org.openstack4j.openstack.identity.internal.DefaultEndpointURLResolver.resolveV3(DefaultEndpointURLResolver.java:120)
	at org.openstack4j.openstack.identity.internal.DefaultEndpointURLResolver.findURLV3(DefaultEndpointURLResolver.java:70)
	at org.openstack4j.openstack.internal.OSClientSession$OSClientSessionV3.getEndpoint(OSClientSession.java:412)
	at org.openstack4j.core.transport.HttpRequest$RequestBuilder.build(HttpRequest.java:405)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:192)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:187)
	at org.openstack4j.openstack.identity.v3.internal.ProjectServiceImpl.list(ProjectServiceImpl.java:65)
...
`
how can i fix this?
thanks

**Comment by ayberkcal** [comment]
Can you debug OSClientV3 like that:
http://i.imgur.com/lx044u8.png
and sure to ip or hostname reachable from your computer.

**Comment by SevenLin** [comment]
Thanks you very much ! finally,i found the reason,i have not enough permission

**Comment by auhlig** [comment]
Thanks @ayberkcal. Can this be closed @SevenLin?

**Comment by SevenLin** [comment]
sure,no problem
